### ISSUE TITLE
Search broken on Android Q

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#100]
I upgraded to Android Q last week.  After the upgrade, I get a toast message from Music Control

"There is No Connection to WiFi"

This happened on two different networks that worked previously prior to the upgrade.  I suspect that Android Q requires an additional permission to get broadcast messages but it never prompted me for an additional permission.

**Comment by mrlad** [comment]
If I manually input the IP address, everything works, so it seems like just scan is broken right now.

**Comment by mkulesh** [comment]
Hi @mrlad 
I hope I fixed this problem within this issue: https://github.com/mkulesh/onpc/issues/95
Today, I deployed new release 1.7 that includes this fix. May be, the new version (1.7) is already available on Google Play. If yes, could you please update the app?

**Comment by mrlad** [comment]
It is indeed fixed!  Just downloaded 1.6 and its working.  The Wifi fix is listed in the changelog but the version number differs from what you mentioned.

**Comment by mrlad** [comment]
I'm sorry, I didn't see 

https://github.com/mkulesh/onpc/issues/95

when I reported this.

**Comment by mkulesh** [comment]
you are right, the latest released version is 1.6. Sorry for typo in my last message.

**Comment by mkulesh** [comment]
If WiFi works as desired, could you please close this issue? With this fix I hope that VPN shall also work as desired (we discussed this problem a half of year ago, see https://github.com/mkulesh/onpc/issues/28)

**Comment by mrlad** [comment]
Its working on Android Q now with the official play store version.
