### ISSUE TITLE
Friendly Name doesn't show under Media Inputs (iOS)

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#101]
The Friendly name does show when searching (nice touch!) and also in settings.  However, it doesn't show under Media Inputs.  Double checked and the latest Android release doesn't have this bug.

Testing this on an iPad Pro with iOS 13.2.3

**Comment by mkulesh** [comment]
Hi @mrlad, thank you for observation. I fixed it. Starting from the version 2.0.1, the friendly name shall be also used in under Media Inputs. The Android version is uploaded (see https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v2.0-release.apk). The iOS version is uploaded to the TestFlight too but waits to be approved.

**Comment by mrlad** [comment]
I see the friendly name now under media inputs!
