### ISSUE TITLE
Trick icons at the bottom are small on an iPad

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#102]
The row of trick icons at the bottom of the screen are sized for a phone and not a tablet.  Would be nice if the icon size could be adjusted based on the resolution of the device.

This isn't a show stopper though.  The icons are legible but smaller.

**Comment by mkulesh** [comment]
Hi @mrlad, in the app settings, I added new parameter "Text and buttons size". 
![image](https://user-images.githubusercontent.com/30557348/70275563-aba9c600-17ae-11ea-92ad-bf6d313a86f0.png)
For my iPad, the "Huge" size looks really good: 
![image](https://user-images.githubusercontent.com/30557348/70275634-d4ca5680-17ae-11ea-83d9-969b10a205fb.png)
Could you try different size?

**Comment by mrlad** [comment]
Looks great on my iPad also!

**Comment by mkulesh** [comment]
Implemented as a part of https://github.com/mkulesh/onpc/issues/77
