### ISSUE TITLE
Onkyo NS-6170 / A-8870

### ISSUE THREAD

**Issue by mm-in-ch** [mkulesh/onpc#103]
The network player NS-6170 works together with the app perfectly, too.

The A-8870 amplifier from the earlier 1990s completely ignores any orders given to it via the "RI" section of the app. But it does that as well when using the NS-6170's remote. So, this doesn't look like a flaw of the app.

**Comment by mkulesh** [comment]
Hi @mm-in-ch,
I use NS-6130 also with an external amp (A-9010) and everything works fine. However other people reported that not all modern players or receivers support the access to the external amp via network. This information is available in the receiver information. Could you please activate the "Developer options" in the app settings and than open the "Receiver Information" from the main menu. You will see an xml where near to the end shall exist following parameters:
<control id="AMP Control(RI)" value="1" />
<control id="CD Control(RI)" value="1" />
value = 1 means (like in my NS-6130) that external amplifier is accessible via network. value = 0 means that amp is not accessible. That do you have for your NS-6170?

**Comment by mm-in-ch** [comment]
While the function to control the amp is switched on, the amp does not react. Please find attached a screenshot from my tablet 

![1Screenshot_20191206-161714](https://user-images.githubusercontent.com/58570991/70335398-83ba7100-1847-11ea-98d2-76b7e86c6fac.png)

**Comment by mkulesh** [comment]
Hi @mm-in-ch, thank you for screenshot. Yes, the NS-6170 like my NS-6130 shall accept commands for the external amp control. How does the official Onkyo Controller work? In the device menu, the official app has an item "Control Device" that has exactly the same buttons for external amplifier like in my app. Do amplifier react if you press these buttons in the official app:
![Screenshot_20191206-220644](https://user-images.githubusercontent.com/30557348/70356539-e83ff500-1874-11ea-839e-44553d83af3d.png)
![Screenshot_20191206-220711](https://user-images.githubusercontent.com/30557348/70356557-eece6c80-1874-11ea-827a-e5b8a9101258.png)

**Comment by mkulesh** [comment]
Information missing, no response.
