### ISSUE TITLE
Missing EXTRA1 input selector

### ISSUE THREAD

**Issue by schmidtch89** [mkulesh/onpc#111]
Most receivers have two input selectors which are called EXTRA1 and EXTRA2. My Teac AG D500, which is a rebranded Onkyo TX NR 515, listen to SLI07 for input selector EXTRA1. I checked this with this project: https://github.com/miracle2k/onkyo-eiscp.
Can you please add SLI07 to your default list https://github.com/mkulesh/onpc/blob/master/app/src/main/java/com/mkulesh/onpc/iscp/messages/InputSelectorMsg.java?
Looks like we need the following added line 45: **EXTRA1("07", R.string.input_selector_extra1),**

UPDATE:
After having a second look I also found the input selector for EXTRA2. Didn´t work at my receiver the first time because you need to assign a HDMI input for that source to enable it.

So I kindly ask you to attach also the following line: **EXTRA2("08", R.string.input_selector_extra2),**

**Comment by mkulesh** [comment]
Hi @schmidtch89,

I added two additional selectors (EXTRA 1 and EXTRA 2) in the default selector list. Could you please test the latest auto-build from here: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.8-debug.apk

**Comment by schmidtch89** [comment]
Hi @mkulesh ,

I checked your build 1.8 and it works excellent.
Thank you for your quick response.

**Comment by mkulesh** [comment]
To be merged in iOS release

**Comment by mkulesh** [comment]
Released in v.1.8
