### ISSUE TITLE
One-Click Restore of Group Configurations?

### ISSUE THREAD

**Issue by seb314** [mkulesh/onpc#112]
Is the an option to quickly restore frequently-used speaker-group configurations? If not, any hints about what I should consider when implementing such an option?

I imagine something like a button on the home-screen that automatically connects/disconnects my three speakers and sets the appropriate ST/FR/FL channels.

Background: we use the group function to connect 2 additional onkyo speakers (left and right channel) to the main hifi device. This group seems to be deleted every time when one of the devices is used via the chromecast protocol, and needs to be removed manually for the TV setup to work properly. 
Therefore we end up creating and deleting the same group configuration over and over again.

**Comment by mkulesh** [comment]
Hi @seb314,
thank you for this issue, I think it is a great idea to add some settings hat allows to quickly restore the group configuration. Currently, I am preparing iOS release that is not really easy and would happy if you could implement this and just submit me a merge request. 

From my point of view the appropriate GUI solution is add some text field with into "Group/Ungroup devices" dialog, see image:
![group_ungroup](https://user-images.githubusercontent.com/30557348/71767652-9b504c80-2f0e-11ea-8d9f-b547749b4484.png)

The button in the right on text field opens a dialog that shows all pre-saved setting names. The user can also write the new name in this field. If the name is not empty, buttons "SAVE" and "DELETE" in the bottom of dialog appear. The "SAVE" button saves the settings in the preferences and apply them. "DELETE" button allows to delete this settings from the preferences.

That do you thing about this design?

**Comment by mkulesh** [comment]
No response
