### ISSUE TITLE
Consider a volume slider

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#12]
The single step up/down buttons for volume control are nice for fine grained volume control, but it would be nice if there was a volume slider for rapid changes in between the single step up/down buttons.  The official Onkyo app has a slider for its volume control.

**Comment by mkulesh** [comment]
good idea, I can implement it, but for release 0.8 (we already have a lot of new functionality that can be released in 0.7)

**Comment by mrlad** [comment]
Agreed. This is fine for 0.8.

Do you have a roadmap of major features you want to add for 0.8, 0.9 and 1.0 yet?

**Comment by mkulesh** [comment]
Hi @mrlad, as a first step that will be also delivered with revision 0.7, I added the possibility to change the master volume using hardware buttons (volume keys) on the android phone or tablet. This option is now available in the configuration, by default switched off.

![volume_keys](https://user-images.githubusercontent.com/30557348/52884659-ddde2e80-316e-11e9-95c5-e626cab0881c.png)

**Comment by mkulesh** [comment]
Hi @mrlad, now, you can press on the master volume label (text) on the MONITOR tab. Master volume dialog will appear, where you can use the slider. I am not sure whether the maximum on the slider corresponds to the volume maximum on the receiver. Could you please test how this slider works?

I suggest to keep this design with popup dialog from two reason:
- There are no free space for addition slider on the MONITOR tab in the landscape orientation
-  We can later add in this dialog additional sliders for Bass and Treble (there are totally 7 zones where Bass/Treble can be changed: Front, Front Wide, Front High, Center, Surround, Surround Back, Subwoofer). A dialog has enough space to place all these sliders

![master_volume](https://user-images.githubusercontent.com/30557348/53200619-42dbcd80-3622-11e9-9c3a-782d61113cde.png)

![master_volume_dlg](https://user-images.githubusercontent.com/30557348/53200622-4707eb00-3622-11e9-860f-3a39bb284361.png)

**Comment by mrlad** [comment]
The pop up slider works.  However, there are two issues:

1. The volume scale is 0 to 130 not 0 to 100 (don't think its properly factoring in the 0.5 step increments like we worked out with the incremental volume buttons).
2. Its not at all obvious that the master volume slider will pop up when you tap on it.  If you didn't tell me, I never would've even guessed it was there or never would've tapped on it.

**Comment by gomanuke** [comment]
For me it's a pretty smart solution) And You are right about hidden feature... But from the other hand would You suggest a place for slider?

**Comment by mrlad** [comment]
@gomanuke , unfortunately, I'm not sure there is a good solution.  Unless the slider is visible, many people won't its there (unless they're curious).  The only way to know for sure is to try it on people that aren't aware of the popup and see if they intuitively discover it.

**Comment by gomanuke** [comment]
Well, my present idea is: long type press on volume buttons calls Slider. I guess it's intuitive enough.

**Comment by mkulesh** [comment]
Hi @mrlad, @gomanuke, that do you think about this solution?

![master_volume](https://user-images.githubusercontent.com/30557348/53274119-65d7b180-36f6-11e9-99eb-d47b45210c0f.png)

**Comment by mrlad** [comment]
That icon is definitely better.

**Comment by gomanuke** [comment]
Sure it's better. And please think about long press too. The matter is that it's partially intuitive thing to wait a faster activity from long press IMHO...

**Comment by mkulesh** [comment]
Hi @gomanuke, long press is done and ready for test

**Comment by mrlad** [comment]
@mkulesh , is long press functional now?  Cause its not working for me.

**Comment by mrlad** [comment]
Also, the master volume scale is definitely not working on the 30.7. 40.7 or 5.2.  If I drag all the way to 0, its still audible.  If I max volume, its barely audible and the scale is 0-130 on these devices.  More confirmation that there's something wrong w/the 0.5 step increments and the slider

**Comment by mkulesh** [comment]
Hi @mrlad, yes, long press on up/down buttons shall work in the latest nightly build. It was unfortunately a bug when slider is dragged to 0, now it is fixed. I also tried to fix 0.5 scaling problem. Please test, I hope it works now.

If the scaling still not work I need more precise observations. Please than observe following situation:
- If you sets master volume on _receiver_ to 50% . That is sown: a) on receiver display, b) in onpc on DEVICE tap, c) that is the slider position in the master volume dialog, d) that value is displayed in right of slider in the master volume dialog?
- If you sets master volume on _receiver_ to 100% (maximum) . That is sown: a) on receiver display, b) in onpc on DEVICE tap, c) that is the slider position in the master volume dialog, d) that value is displayed in right of slider in the master volume dialog?

**Comment by mrlad** [comment]
The step level controls work to control the volume in 0.5 increments.  They are scaled correctly from 0 to 100.

1. The volume slider scale is 0 to 130 (which is the same scale as the step controls were prior to your fixes to handle 0.5 increments)
2. Sliding the scale all the way to 0 does nothing.
3. The lowest level I can use on the slider is 11 (slider works between 11 and about 120).  Changing the slider in this range affects the receiver volume
4. When the slider changes, the actual receiver volume is about 1/2 the value of the slider.
5. When moving the slider all the way right, it seems to stop around receiver volume level of 60 or so.

**Comment by mkulesh** [comment]
Hi @mrlad, I think you use not the actual version. Could you uninstall the app completely and install this version: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.8-debug.apk
I expect that the maximum value of the slider is 100, not 130

**Comment by mrlad** [comment]
You were correct.  The latest version is working as you would expect.

That being said, long press isn't bring up the master volume.  Only a tap

**Comment by mkulesh** [comment]
It shall be a long press not on the master volume label (a number with a slider icon), but on the volume up/volume down keys. Long press is enabled if receiver is on. Did you tried the long press on these keys?

**Comment by mrlad** [comment]
Long press on the keys worked.

**Comment by mrlad** [comment]
Working well in the release candidate

**Comment by mkulesh** [comment]
Released in v0.8
