### ISSUE TITLE
Please use device friendly name

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#13]
Would like to see this info in two places

1. In the device tab
2. Option in settings to show either the model or the friendly name on the main screen

This info is in the official app and the DTS PlayFi app so it does appear to be part of the API.

**Comment by mkulesh** [comment]
good idea, I can implement it, but for release 0.8 (we already have a lot of new functionality that can be released in 0.7)

**Comment by mrlad** [comment]
Agreed.  I wouldn't hold 0.7 up for this.

**Comment by mkulesh** [comment]
Hi @mrlad, I started with this issue and added the possibility to change the friendly name in device tab. If this name is not empty, it will be shown in the toolbar. If the name is empty, the model will be shown as before. Currently, there are no setting to switch that will be shown. Do we really need such a setting?

![friendly_name](https://user-images.githubusercontent.com/30557348/52905678-c9b53280-323d-11e9-8c9c-38ed3820b02f.png)

**Comment by mrlad** [comment]
@mkulesh if you are showing the friendly name in the title bar (and your screen cap shows that you are), you've met my requirement.

**Comment by mkulesh** [comment]
Hi @mrlad, than I will say that this issue is implemented, please test.

**Comment by mrlad** [comment]
Is this in 0.8 or the official 0.7?

**Comment by mkulesh** [comment]
Hi @mrlad, this is new nightly build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.8-debug.apk

**Comment by mrlad** [comment]
@mkulesh this is working for me now.  Thanks.

**Comment by mrlad** [comment]
In the daily 0.8 build from Monday, I'm able to change the Friendly name on the DRX 5.2, but attempts to change the Friendly name on the DTR 30.7 or DTR 40.7 seem to fail (i.e. the name doesn't change).

Do you need a log to help debug it?

**Comment by mkulesh** [comment]
Hi @mrlad, I checked the documentation. Generally, there are two messages: "NFN" that allows to change "friendly name" and "NDN" that just returns the "NET/USB Device Name". I have no idea that is the difference between these two names. Currently, I use "NFN" only. The documentation says that both messages are applicable for DRX series (see file https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_140.xlsx for more details), but there are no information whether  DTR x.7 or DTR x.7  support it. I have some questions:
- Does official Onkyo app allows to change names for DTR x.7 or DTR x.7 and than correctly show them? 
- In onpc, could you please activate "Developer mode" in settings and observe the "Receiver information" from the menu? There is an attribute "friendlyname". Is it filled on  DTR x.7 or DTR x.7? If filled, is it changed if you send new name from the onpc, close the app and than starts app again?
-  If official Onkyo app shows friendly name, is it changed if you change it in onpc and than restarts official Onkyo app? 
- If official Onkyo app allows to change friendly name, does onpc show new name? Does "friendlyname" in 
"Receiver information" in onpc change accordingly if you restarts onpc?

**Comment by mrlad** [comment]
_* Does official Onkyo app allows to change names for DTR x.7 or DTR x.7 and than correctly show them?_

It neither shows nor allows you to change the friendly name.  However, I don't know if that is a problem with the app or the receiver because the older receivers only work with the Integra Controller app.  And the Integra Controller doesn't work with the DRX 5.2.  This is with the Android Integra Controller app.  The next time I'm on site, I'll check how the iOS Integra Controller app behaves.

I can see the Friendly Name in the device settings menu and via the very limited Web UI.  I can also see the device using the Friendly name when it advertises itself on the IP network via MAC scans etc.

**Comment by mkulesh** [comment]
Hi @mrlad, could you please send me per email whole content of the "Receiver information" dialog for DTR x.7 or DTR x.7? 

If you changes the name in the DEVICE tab in the app and than press the button "Change friendly name", the content of the field "Friendly name" is changed or new entered value is lost and previous value restored?

I slightly changed  the parameter "Friendly name" in the app Settings. Now, this parameter impacts both friendly selector names in the MEDIA tab as well as device name in the toolbar:

![friendly_names](https://user-images.githubusercontent.com/30557348/53199398-44f05d00-361f-11e9-9618-00ec625c8251.png)

**Comment by mrlad** [comment]
_If you changes the name in the DEVICE tab in the app and than press the button "Change friendly name", the content of the field "Friendly name" is changed or new entered value is lost and previous value restored?_

On the 30.7 and 40.7, the field is empty.  Suspect this is the primary problem.

**Comment by mrlad** [comment]
@mkulesh , I emailed you the receiver info for both the 30.7 and 40.7.

To be clear, when the app starts up, the Friendly Name field is blank (even though I see it in the Receiver Info XML) .

**Comment by mrlad** [comment]
and oddly enough, I don't see the Friendly Name in the receiver info XML for the DRX 5.2 but I do see it in onpc!

**Comment by mkulesh** [comment]
Hi @mrlad, in the ISCP, there are three (!!!) places where names are presented: Friendly Name Setting Command (NFN), NET/USB Device Name Command (NDN), and the attribute "friendlyname" in
"Receiver information" message. Previously, I only used NFN that seems to work on some receivers but is empty on  30.7 and 40.7. On the other hand, 30.7 and 40.7 have filled "friendlyname" in
"Receiver information". Now, I added the fallback to this attribute if NFN is missed. If it will not work, I will also add a fallback to the NDN message that is empty for my network player. Could you please test the latest build?

**Comment by mrlad** [comment]
@mkulesh with the latest build, I see the friendly name for both the 30.7 and 40.7

**Comment by mkulesh** [comment]
Hi @mrlad, are you able to change it using "Change friendly name" button in the DEVICE tab?

**Comment by mrlad** [comment]
I didn't try to change it, I thought your test was read only.  I can't try easily now because I'm LTE only at the moment and I can't connect via VPN to try it out (see my other issue).

**Comment by mrlad** [comment]
I'm unable to change the friendly name on the 30.7 or 40.7

**Comment by mkulesh** [comment]
> I'm unable to change the friendly name on the 30.7 or 40.7

It means these receivers do not support Friendly Name Setting Command (NFN) that is inline with the protocol documentation. Unfortunately, we can not fix it.

**Comment by mkulesh** [comment]
Released in v0.8
