### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [mkulesh/onpc#138]
Dear developer
In the process of using, I found a bug in layout / display. The text of "not connected" in the second line is half blocked, which may be an adaptation problem.
App version is 1.10, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. 
Thank you!
![image](https://user-images.githubusercontent.com/18572115/78697921-1b35ea80-7934-11ea-9e5a-2fa4cf3eb171.png)

**Comment by mkulesh** [comment]
Hi @franklinbill,
thank you for the issue. I will try to reproduce and solve it.

**Comment by mkulesh** [comment]
Hi @franklinbill 
it is now fixed. Could you please install the latest nightly build from here:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.12-debug.apk
and test how it now works for you?

**Comment by franklinbill** [comment]
It is ok! thank you!

**Comment by mkulesh** [comment]
Released in version 1.12
