### ISSUE TITLE
Add master volume slider on LISTEN tab

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#139]

**Comment by mkulesh** [comment]
Added a new option "Device (Slider)" to the "Sound control" list:
![slider_settings](https://user-images.githubusercontent.com/30557348/79043098-4d2da200-7bfd-11ea-988a-79fbfbcf8902.png)

Id this option is selected, the app shows a master volume slider instead of "+" and "-" volume buttons on the LISTEN tab:
![volume_slider](https://user-images.githubusercontent.com/30557348/79043122-8a922f80-7bfd-11ea-9f89-ef659f7db40c.png)

**Comment by mirml** [comment]
Great, thank you.

**Comment by mkulesh** [comment]
Released in versions 1.12 and 2.3
