### ISSUE TITLE
Text from Largest Font Size Cut Off

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#14]
Some text fields are cut off when the system is set to the largest font size.

Most fields in the Device tab have cut off text.

Brand, Model and Year are fine.  

The device, Device Info, Firmware and Google cast settings are cut off on that tab.

Media and Monitor tabs are fine.

Settings are ok

**Comment by mkulesh** [comment]
thanks, I will fix it

**Comment by mkulesh** [comment]
Hi @mrlad, the layout is now adapted for the larger font:
![large_text](https://user-images.githubusercontent.com/30557348/52537292-50ad6b00-2d65-11e9-862b-661364420776.png)

**Comment by mkulesh** [comment]
Released in v0.7

**Comment by mrlad** [comment]
Confirmed fixed.  Thanks.
