### ISSUE TITLE
Support Older Pinoneer Models

### ISSUE THREAD

**Issue by tpascaru** [mkulesh/onpc#149]
Hi,

Wondering if it's possible to add support for some older Pioneer Models?
I have a VSX-1121, and it accepts commands on telnet port 23:
https://raymondjulin.com/blog/remote-control-your-pioneer-vsx-receiver-over-telnet

Or more generally, it seems to support this command-set which is somewhat similar to the integra commands.
http://www.pioneerelectronics.com/StaticFiles/PUSA/Files/Home%20Custom%20Install/VSX-1120-K-RS232.PDF

**Comment by mkulesh** [comment]
Hi @tpascaru,

I looked into the attached documentation. Unfortunately, the difference between the message format and commands of the older Pioneer Models and the actual ISCP protocol used in new Pioneer and Onkyo/Interga models is huge. The app supports currently ISCP protocol only. 

Furthermore, I do not have any older Pioneer device and is not able to debug and test any implementation related to this older protocol.    

However, I can support any developer who has such a model and is able to implement this functionality. My app is distributed under GPLv3 license and it is completely legal to fork the app and replace communication protocol. I put this issue in state "Help wanted" for a half of year. May be somebody who has interest see it and will implement this feature.

**Comment by rachit-mathur** [comment]
Hi,
Tried with Pioneer SC-95 receiver that was released in 2016 so 4+ years old now but it did not connect. Do you know if your app will be compatible with this receiver?
Thanks!

**Comment by rachit-mathur** [comment]
Thanks for your reply!

**Comment by mkulesh** [comment]
Actual documentation about Pioneer receivers is not available. Due to missed documentation, issue can not be implemented

**Comment by seuf** [comment]
My pioneer VSX-924 is not recognized :(
I've tried to manually connect (192.168.1.23:8102), but not working.
Is this model compatible ?

**Comment by mkulesh** [comment]
Hi @seuf,

at the moment I have no information about VSX-924. Nobody has reported that my app works or does not work with this model. The Onkyo network protocol is not really stable. I suggest to read this page https://github.com/mkulesh/onpc/wiki/Connection-problems and try to reset the receiver. If this does not help means that my app is unfortunately not compatible with your device.

**Comment by seuf** [comment]
I have the old iControlAv5 app (on the play store) which work, but the app is ~ugly~ not really user friendy.

**Comment by mkulesh** [comment]
Hi @seuf 
I can understand it, but have no possibility to expand my app in order to support the older Pioneer models. It has different network protocol in comparison to the modern Onkyo protocol used by the app. As I wrote above, full documentation about this older protocol is not available. It means some reverse engineering in necessary in order to capture the protocol. I have no Pioneer devices to do it.

**Comment by seuf** [comment]
No pb, i anderstand. Thanks for your answer !
