### ISSUE TITLE
TD-NR 626

### ISSUE THREAD

**Issue by jd778** [mkulesh/onpc#156]
Controller works but sound goes silent every  30 secs  any thoughts?

**Comment by mkulesh** [comment]
Hi @jd778,
in the app, I have no code that make sound silent every 30 seconds... May be some problem that the app or receiver have corrupted state... I suggest to do following:
1. Completely uninstall the app and install it again fro Google Play or F-Droid
2. Ensure that you use the latest firmware version on your receiver. If not, update the firmware.
3. Many people report that Onkyo firmware may work unstable and the factory reset of the Onkyo device sometime helps.
4. If all these steps can not help, could you please collect the app logging (as described here https://github.com/mkulesh/onpc/wiki/Collect-Logs) where sound goes silent and send it me per Email on mikhail.kulesh@gmail.com

**Comment by mkulesh** [comment]
Closed since there is no feedback
