### ISSUE TITLE
Possible to have volume slider AND +/- concurrently?

### ISSUE THREAD

**Issue by tpascaru** [mkulesh/onpc#159]
There is a setting for Sound Control for "Device" or "Device (Slider)". Sometimes, I like the slider, sometimes (for small tweaks), I like +/-. Any way to get them both at the same time?

Thx!

**Comment by mkulesh** [comment]
Hi @tpascaru, thank you for proposal. Yes, the way get them both at the same time exists. The app has a setting "Use volume keys to change master volume on remote device". This setting was previously at the and of settings list, I moved it now in the "Audio control" section, see screenshot below. However, here was a bug: this setting was ignored, if "Device (Slider)" was selected. I also fixed this bug. It means, if the setting "Volume keys turning" is activate, you will be able to tweak master volume on the remote device using hardware buttons "Volume +/-" on your smartphone. Could you please install the latest auto build (https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.14-debug.apk) and test whether this solution is usable for you? 

![audio_control](https://user-images.githubusercontent.com/30557348/86834770-8316e100-c09b-11ea-9ed8-8c8d164d6d0a.png)

**Comment by tpascaru** [comment]
Hi -- thanks for the reply. I just installed the app you suggested, and the
external volume keys don't work. I will say that I have an app called
"Volume Panel" installed which inserts some functions on the keys, so there
might be some conflict.

It would certainly be a work-around for having both options. I am wondering
if it's possible to have the slider and the +/- GUI controls on at the same
time? That would be a better use case for me. Although, the app works
really well as it is and it's a 1000% improvement over the Onkyo app, so
thanks for that!

Regards
-Ted

**Comment by mkulesh** [comment]
Hi @tpascaru,
no problem, I will add today these buttons near to slider and provide you new debug version. You observation with "Volume Panel" app is interesting. Could you please temporary remove this app and than test whether my app can than receive external volume keys events?

**Comment by mkulesh** [comment]
Hi @tpascaru, I added new option "Device (Buttons and Slider)" in the sound control settings. If this option is selected, the app shows additional buttons + and - near to the slider:
![sound_control](https://user-images.githubusercontent.com/30557348/87181086-00cc2e00-c2e2-11ea-85bd-16beafced296.png)
![buttons_and_slider](https://user-images.githubusercontent.com/30557348/87181136-15a8c180-c2e2-11ea-94d1-aed02fef6974.png)
In order to test it, please install the latest debug build (https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.14-debug.apk)

**Comment by tpascaru** [comment]
Hi! Thanks for the update. It works great, and it's really nice how you
implemented the +/- on either side of the slider. It makes it more obvious
where to press! I also uninstalled my other volume manager, and now the
hardware button control works. It seems to work when the application is in
the foreground (i.e. if another app is in the foreground, or the phone is
in standby, the buttons do not work). I presume that is the intended
behavior.

Also -- I had to install the play store application yesterday so I can
sideload your debug version. Today when I did it, I still had to manually
uninstall first, and then play-protect gave me a warning (I ignored it).

Thx for the development! Your app is a great find :)

Regards
-Ted

**Comment by mkulesh** [comment]
Commit aef309a7ef32ec4bb2c77ff18220dd17099b8934 shall be merged into iOS branch

**Comment by mkulesh** [comment]
Released in v.1.14

**Comment by mkulesh** [comment]
Released in iOS v.2.5
