### ISSUE TITLE
Add shortcuts for TuneIn into navigation drawer

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#166]

**Comment by mkulesh** [comment]
- Added new context menu for the media list item within 1st and 2nd layer (like "My presets" in TuneIn). Up to 6 shortcuts can be added
![create_shortcut](https://user-images.githubusercontent.com/30557348/91909093-e2186100-ecac-11ea-9ee0-93a3c6efded2.png)
- All available shortcuts are presented in the Navigation Drawer:
![shortcuts](https://user-images.githubusercontent.com/30557348/91909235-1db32b00-ecad-11ea-8ec1-5e64dfb53e92.png)

**Comment by mkulesh** [comment]
Released in v1.15

**Comment by mkulesh** [comment]
Released in iOS version 2.6.3

**Comment by medikoo** [comment]
Great thanks for this feature @mkulesh ! I was about to request that and I found this PR 👍

**Comment by mkulesh** [comment]
Hi @medikoo,
you are welcome! Just install the latest version of the app: 2.6.3 on iOS or 1.16 on Android for this feature!
