### ISSUE TITLE
Support menus & remote control keys

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#17]
The official Onkyo app lets you get into/out of menus via a soft remote.  Would be nice if this could be done with onpc too.  This is a feature request for 0.8 or later.

**Comment by mkulesh** [comment]
Hi @mrlad, I do not unfortunately know this functionality. That do you mean "into/out of menus"? The app menu or a receiver menu?  That is "via a soft remote"? A software keyboard on the Android device or something else?

**Comment by mrlad** [comment]
I'm referring to the Menu and Quick Menu (typically accessed by the Setup or Menu buttons on the remote).  When these keys are pressed on the remote, a receiver configuration menu is displayed on the screen.  These menus typically allow you to change things like friendly name, setup sources, download updates etc.

By soft remote, I meant emulate keys on the Onkyo remote control.

**Comment by mrlad** [comment]
@mkulesh do you have access to the Integra Remote app or the Onkyo Remote app by Onkyo?  It has an implementation of the virtual remote control for accessing menus.

**Comment by mkulesh** [comment]
Hi @mrlad, unfortunately,  Onkyo Remote app does not work with my network player, it shows an error "The device you have can not be operated by this app. Please use Onkyo Controller". The same problem is with Integra Remote app. 

Actually, it is not too difficult for me to add a new tab (like "RC", the visibility is configured in the Settings). As an example, please try to activate "Remote Interface" in the settings.

However... For my network player, I never used remote control to access Menu since all settings available in this menu are already presented in the DEVICE tab. Only friendly name is missed, but it can be changed using a message ("NFN" - Friendly Name Setting Command). My idea for #13 was just add an edit field in the DEVICE tab with a button "Submit"; i.e this field and button are used in order to edit and submit friendly name - no access to receiver Menu is necessary. 

The same solution for Firmare Update. The button to update firmware exists already in the DEVICE tab and is visible if new firmware version is available. No access to receiver Menu is also necessary. 

All other settings from receiver Menu can (and, I think shall) be added in the Setting panel of DEVICE tab. I suggest to add first the friendly name field and all settings for your device and than discuss again whether this new RC still be necessary.  That do you think? Could you please list which settings are presented in your receiver menu?

**Comment by mrlad** [comment]
@mkulesh, I think its a good idea to allow the friendly name to be changed in the device tab.

Just be aware that:

1. Different receivers will have different menu options.  I don't think you can address all possible menu options.
2. There are dozens of options in these menus.  Changing the friendly name for each source, changing the volume level for each speaker, running EQ tests.  I'll try to collect a list when I have access to the receiver so you have an idea of all the options.

Maybe you can put the most common ones in a tab(s)?

**Comment by mrlad** [comment]
Almost all of the menu settings are one time use only.

These are menu items that I personally would change once my configuration is setup

 Speakers
  Level Calibration  <--- this sends a test tone to the speakers as a volume level check

Miscellaneous
  Firmware Update

**Comment by mkulesh** [comment]
Hi @mrlad, I agree we only need 5-7 most common options in the DEVICE tab. As I wrote Firmware Update is already exists, just invisible until new firmware will become available.
From previous log you send me I see following options available in your model that can be added:
- "MOT" - Music Optimizer / Sound Retriever
- "RAS" - Re-EQ/Academy Filter Command 
- "PCT" - Phase Control
- "ITV" - IntelliVolume / Input Volume Absorber
- "AEQ" - AccuEQ
Is it meaningful to add these option or nobody needs it?
Could you please produce and send me log where you only change options that can be added in DEVICE tab (no playback, just change settings from receiver)?

In parallel, I can add a tab RC that emulates RC.

**Comment by mrlad** [comment]
Hi @mkulesh. Those options may be useful for some, but not useful for me.   I really need to setup InteliVolume but that appears to be something that you setup once and then never adjust.

AEQ is a setup option.  Most Auto-EQ when they install and then don't alter unless something in their configuration changes.

Its good to know the firmware update option is already supported.

**Comment by mrlad** [comment]
_Could you please produce and send me log where you only change options that can be added in DEVICE tab_

Can you please clarify?  Which options would you like the log for?

**Comment by mkulesh** [comment]
Hi @mrlad, I mean if you wish to have any options from your receiver menu visible in DEVICE tab, I need to know which messages are related to these settings: I need logging where these settings are changed in the receiver menu. But may be you are right - just new RC tab may be enough. I will implement RC tab first and than we will see whether we need to duplicate any settings in DEVICE tab.

**Comment by mkulesh** [comment]
Hi @mrlad, I started to implement this issue. The first prototype is ready. Please note that "Setup" button does not supported by almost all receivers (how I see in the protocol documentation). May be it is meaningful to remove this button. Which button do you wish to add here?

![rc_tab](https://user-images.githubusercontent.com/30557348/53274297-13e35b80-36f7-11e9-870d-a4027d5f755a.png)

**Comment by mkulesh** [comment]
The name of MONITOR tab is now too long and, therefore, smaller than other names... Could you suggest a shorter variant this tab name instead of MONITOR?

**Comment by gomanuke** [comment]
MUSIC
PLAY

**Comment by mrlad** [comment]
Initial feedback:

1. Are the buttons functional?  Cause they don't do anything on my 5.2.
2. The buttons are very small.  Can they be made larger?
3. As far as the menus, there are two primary menus...Setup and Quick Menu.  Personally, I'd like both but I could live w/just Quick Menu

**Comment by mrlad** [comment]
IDK about PLAY @gomanuke , some of my sources aren't Playback.  Ditto for MUSIC (sources with A/V--doesn't seem right for MUSIC).

How about these

AUDIO
LISTEN

but its longer than MUSIC and has the same problem of audio centricity.

**Comment by mrlad** [comment]
FWIW The official app uses the term 

Audio Adjust

**Comment by mkulesh** [comment]
Hi @mrlad, I am so sorry... My initial implementation was based om wrong message. This message is partially work on my network player. However, I dumped today the IP traffic from official onkyo app and noted that it use other message. This message, however, does not support the numerical keys. 

Now, I expect that all keys on RC tab will work on your receiver. Just note that "Menu" is a track menu available only if a track is playing and selected on the display of receiver. I also renamed the MONITOR tab to LISTEN. Now it looks much better. 

![rc_tab](https://user-images.githubusercontent.com/30557348/53303063-3778e400-3866-11e9-88ea-1baaddeca957.png)

**Comment by mrlad** [comment]
OK, the setup menu works and works nicely for me.

Is it possible to support the quick menu?

**Comment by mkulesh** [comment]
Hi @mrlad, done. I replaced track menu on the tab RC by quick menu since this track menu button is already exists om the LISTEN tab. Unfortunately I cannot test  quick menu since my player does not support it. Please test.

**Comment by mrlad** [comment]
The quick setup button works @mkulesh

**Comment by mrlad** [comment]
One point of feedback. I find myself tapping on the "Menu" "Setup" and "Return" text labels above the buttons and then see that they do nothing.  Would be nice if they also performed the action.

**Comment by mkulesh** [comment]
Hi @mrlad, it is easy, now these labels are clickable. I think the version 0.8 has enough new features. I would like to freeze the code for version 0.8, test it this week and publish a new release at the beginning of the next week. Coild you please re-test all new features more extensive?

**Comment by mrlad** [comment]
@mkulesh , let me know when you have a release candidate ready for testing.

**Comment by mkulesh** [comment]
Hi @mrlad, please use this release build:
https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v0.8-release.apk

**Comment by mrlad** [comment]
Working well in the release candidate including the button text bringing up the menu

**Comment by mkulesh** [comment]
Released in v0.8
