### ISSUE TITLE
Improve user interface for media shortcuts

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#170]
This is a followup issue of https://github.com/mkulesh/onpc/issues/166:
Dealing with MEDIAs in your controller app the user needs to use tabs only. Media selecting in the MEDIA tab. Listening in the LISTEN tab. Selecting shortcuts in the menu is in my opinion a break in this logic. It should be done within working with tabs. Some solutions:
- An own tab: Unlimited number of shortcuts and arrangement of the order - perfect :-).
- Shortcuts in a submenu (up to six) direct to the corresponding device (long press)? Sounds logical and feasible, but the additional long press is also a break in the user interface.
- Shortcuts in the net tab: Direct access like the other devices. Flexible sorting? More than six shortcuts, may be more?

**Comment by mkulesh** [comment]
The navigation drawer seems limiting - a separate tab might well be better - with no limit on how many shortcuts you can have. Not sure if you'd want a filter like "show me only NET-related shortcuts now" - some people might like it - whilst for others with few shortcuts, it would just take up screen space.  I'll use shortcuts for NET but also TuneIn radio - could use them for FM radio too - a dedicated tab for them would be great.

**Comment by mastermichi** [comment]
Separate tab would be a good improvement.

But there should be some improvements with or without a seperate tab:

- Delete shortcuts by an own icon (now included in the edit function) 
- The user should confim the deletion of a shortcut 
- There should be a test in the app if a shortcut is already playing so the function must not be started
- One shortcut should only be set once. There should be a test in the app
- Sorting the Shortcuts by the user
- The shortcuts should run in the background - maybe there could be a information for the user by sending a toast
- There sould be a infomation by setting a shortcut, how many shortcuts could be set for example: "Shortcut 1 of 10 set" or someting like that

**Comment by jnkn** [comment]
IMHO the handling of shortcuts should be improved. Users with large media libraries might have the demand of significantly more than six shortcuts (20? 30? unlimited?). The current solution in the app menu might not handle this demand.

1. Shifting shortcut handling in the **context menu** of each device may lead also in this restriction.
2. Integration of shortcuts in the **specific channel tab** will give a channal oriented logic 
3. IMHO handling of shortcuts in a **separate tab** will lead to a more content oriented logic, which I prefer.

I agree to requirements of mastermichi according to shortcut handling. Especially 
- the limitation of shortcuts should be widely increased or unlimited
- there must be a posibility of sorting by the user i.e. like the sorting of tab contend in the settings

**Comment by mkulesh** [comment]
Hi @jnkn, thank you for comment. I agree that the separate "CHANNEL" tab may be a good solution. I plan to release current state since it also contains a major improvements for older Onkyo models, and than improve the user interface in the next version. However, if you have any Android experience, I will be happy for any implementation support :)

**Comment by mkulesh** [comment]
Precondition: allow to sort and hide application tabs (https://github.com/mkulesh/onpc/issues/171)

**Comment by mkulesh** [comment]
Hi @jnkn, @mastermichi,
the first implementation of the shortcut tab is here:
- there is no more constraint on the shortcut number
- you can sort the items within the tab using drag and drop
- edit and delete are available in the context menu
- as before, if a shortcut is selected, the app switch to the MEDIA tab
![shortcuts_tab](https://user-images.githubusercontent.com/30557348/93646875-66861600-fa07-11ea-8432-7e04cdb12c24.png)

Furthermore, there is now the possibility to show/hide and sort the tabs, see https://github.com/mkulesh/onpc/issues/171:
![visible_tabs](https://user-images.githubusercontent.com/30557348/93646931-874e6b80-fa07-11ea-93cd-46a4a16e2cbb.png)

**Comment by mastermichi** [comment]
Hi Mikhail,

it is a good first try.

But the usability of sorting by drag and drop is very low.
Sometimes the focus on an item is lost if you slowly move from one place to an other.
Maybe you can find a better implementation for this feature.

Also we should think about renaming the tabs. If you show all tabs there is not enough space to show the names:

![Screenshot_20200919-123318](https://user-images.githubusercontent.com/68911754/93665392-59544000-fa76-11ea-867e-6ef53bf95d2c.png)

Maybe Icons could be a solution for this problem.

By testing the new version I found a litte bug:
If you sort the tabs the app will not show the last selected tab. It just shows the position of the last selected tab but after sorting it could be an other function / tab.

An other idea could maybe a good improvement to the usability. How about fast changing the shortcuts by using the forward and backward buttons in the listen tab?

**Comment by mastermichi** [comment]
Maybe the "Device" tab could be integrated in the menu, so we could reduce the tabs and solve the problem with to tab names:

![Screenshot_20200919-130643](https://user-images.githubusercontent.com/68911754/93665775-86eeb880-fa79-11ea-9ecf-bcedde1e4d09.png)

**Comment by mkulesh** [comment]
Hi @mastermichi,
thank you for testing. I changed the tabs layout in the portrait mode: now the tabs are scrollable (like in the iOS version of the app)  that shall solve the problem with limited space in the tab bar. Now, it is not necessary to move the DEVICE tab into the navigation drawer. 

You are right, there is the problem with sorting behavior of the items in the shortcut tab. I use here a third-party library that implements the draggable list view and it seems to be this library has a bug. I need more time to solve this problem.

I also was not able to reproduce the bug with missed tab after resorting. Could you please take two screenshots: "Visible tabs" screen in the app settings and main screen where inconsistency between settings and main screen is shown (It just shows the position of the last selected tab but after sorting it could be an other function)

The LISTEN tab contains buttons that have a clear functionality: the playback control for the receiver. The shortcuts, however, are not the receiver functions, it is just an app feature. The separate tab for this feature is OK, but I think it will be confusing when we mix receiver-specific and app-specific features on the same tab.

**Comment by mkulesh** [comment]
Hi @mastermichi,
I also found a bug that triggers an abort of the drag and drop. Now, the sorting of shortcuts shall work properly.

**Comment by mastermichi** [comment]
Hi Mikhail,

there is no missed tab after resorting. After resorting the app shows as active tab not the last active tab but the position where the last active tab was.

Maybe the screenshots can explain what I mean:

![Screenshot_20200920-114127](https://user-images.githubusercontent.com/68911754/93708525-405f9380-fb37-11ea-86ee-ecea82d93a7c.png)

![Screenshot_20200920-114145](https://user-images.githubusercontent.com/68911754/93708530-46ee0b00-fb37-11ea-9a75-b7699db745d3.png)

![Screenshot_20200920-114214](https://user-images.githubusercontent.com/68911754/93708538-50777300-fb37-11ea-87bf-aab18e52eb90.png)

After testing the new version I can confirm that sorting of shortcuts now work properly.

Changing the tabs layout in the portrait mode that the tabs are scrollable solve the space problem.

Good work!

**Comment by jnkn** [comment]
Hello,

sorry for my late answer, I some work and activities with my family. I 
installed the first version yesterday morning and I had the same 
problems with the focus while sorting shortcuts in the shortcut tab. Now 
I installed the persent version from github. The problem is solved! 
Great work! I tried a huge amount of shortcuts and it works well. 
Sorting, remembering position if you leave the tab, deletion of the 
first/last entry.. Well done!

IMHO the shortcut should not be include in the media tab. It gets to 
confusing if you create a large number of shortcuts.

But another topic is back: In the context menu you get after the long 
press at the item for which you like to create a short cut: in the 
German localisation the first lines shows "Hizufügen" instead of 
"Hinzufügen". No major bug :-).

BTW: I'm wondering it the name "Shortcut" is the right one. It also 
could be "Bookmark" or "Favourite". What do you think?

Mikhail: If you are not tired, I have some proposals for other enhancements:

 1. In MEDIA TAB: Switch automatically to LISTEN TAB alters selecting a
    media file an start playing.
 2. Safe options for export of another installation on another device.
 3. Contect volume control with the hardware buttons of the
    smartphone/tablet.

Thanks for coding.

Regards,
Jürgen


Am 19.09.2020 um 22:51 schrieb Mikhail Kulesh:

**Comment by mastermichi** [comment]
@jnkn: "BTW: I'm wondering it the name "Shortcut" is the right one. It also
could be "Bookmark" or "Favourite". What do you think?"

I talked to Mikhail about renaming "Shortcut" to another name. "Favourite" was also one suggestion I had. "Bookmark" does not match because we are talking about something you hear and not read. I am still searching for a better name but I think that "Favorite" could be the solution.

**Comment by mkulesh** [comment]
Released in v1.16, to be merged into iOS branch

**Comment by mkulesh** [comment]
Hi @mastermichi,
Thank you for explanations. Now I see the problem you described above: After resorting the app shows as active tab not the last active tab but the position where the last active tab was. I created a new issue: https://github.com/mkulesh/onpc/issues/174
The second issue https://github.com/mkulesh/onpc/issues/175 is related to the renaming "Shortcut" tab to "Favourite".
This issue (https://github.com/mkulesh/onpc/issues/170) is already released in version 1.16 and I ask you to do not more write here but use the newly created issues for further comment.

**Comment by mkulesh** [comment]
Hi @jnkn,

thank you for feedback:
- "Hizufügen" instead of "Hinzufügen": fixed
- I created a new issue #175 that is related to the renaming "Shortcut" tab to "Favourite".
- In MEDIA TAB: Switch automatically to LISTEN TAB alters selecting a media file an start playing: I am not sure about to make it hard-coded. May be a new setting that allows such a behavior? 
- Safe options for export of another installation on another device: unfortunately, the implementation effort is really huge for this feature relative to the benefits from it. I prefer to spend my time for a feature that gives us more benefits.
- Connect volume control with the hardware buttons of the smartphone/tablet: is already here (in Android version). Just turn on the option "Volume keys turning" in the app settings. For iOS it is not possible since the Apple rules forbid to change the functionality of the hardware buttons on iPhone/iPad.

This issue (#170) is already released in Android version 1.16 and I ask you to do not more write here but create new issues if necessary. The merge into iOS branch is coming soon.

**Comment by mkulesh** [comment]
Released in iOS version 2.6.3
