### ISSUE TITLE
Update Design in Landscape Mode

### ISSUE THREAD

**Issue by mastermichi** [mkulesh/onpc#176]
In Landscape-mode should be a better use of the space so the picture / icon / logo in the tab "Listen" could be better shown.

This is how it is now displayed:

![Screenshot_20200920-162229](https://user-images.githubusercontent.com/68911754/93715720-5ab36480-fb6b-11ea-8e0b-45bce64fbe03.png)

but maybe we can find a better solution like this:

![Screenshot_20200920-162229 - Kopie](https://user-images.githubusercontent.com/68911754/93715800-dad9ca00-fb6b-11ea-834b-7a7d41dbb5c7.png)

**Comment by mkulesh** [comment]
Hi @mastermichi,
thank you, I will plan it for the next release

**Comment by mkulesh** [comment]
Hi @mastermichi,
I implemented it in the iOS version. The new design looks like this:
![landscape_design](https://user-images.githubusercontent.com/30557348/94202354-d1c76080-febd-11ea-88bf-19bf411e9e5c.png)
I will merge it into the Android version a little bit later.

**Comment by mastermichi** [comment]
Looks great.
Good work.

**Comment by mkulesh** [comment]
Released in version 2.7 (iOS and Android)
