### ISSUE TITLE
Negative dB for Volume

### ISSUE THREAD

**Issue by romanneverov** [mkulesh/onpc#177]
If it possible please add option to display volume in negative dB (with minus).

**Comment by mkulesh** [comment]
Hi @romanneverov,
If you changes the master volume, does you receiver show the volume in dB on the build-in display? If yes, is the numerical value shown on the build-in display equal to the value shown in the app? Could you please attach a photo of the build-in receiver display with the volume value and the app screenshot with the same value?

**Comment by romanneverov** [comment]
![изображение](https://user-images.githubusercontent.com/26056005/94009264-e5cf6d00-fdac-11ea-915b-258a2fbe3559.png)

**Comment by mkulesh** [comment]
Hi @romanneverov,
the different values on build-in display and in the app are confusing for me. I would like to discuss it. Could you please write me on mikhail.kulesh@gmail.com or in Telegram (Mikhail Kulesh)?

**Comment by mkulesh** [comment]
Closed since there is no response.
