### ISSUE TITLE
Android Widget with controllable buttons or shortcuts

### ISSUE THREAD

**Issue by Pivek** [mkulesh/onpc#196]
It could be very usable to have a widget which I can attach to screen.
Controllable remote buttons or shortcuts (for specific menu option) will be very helpful.
Some output, like this on amplituner screen, with track title, could be nice feature too.

**Comment by mkulesh** [comment]
Hi @Pivek 
I added widget for shortcuts in the premium version. If you like to test it, please download and install https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v2.9-release.apk

This widget looks like this:
![widget_shortcuts](https://user-images.githubusercontent.com/30557348/103237268-6622e280-4947-11eb-98f0-b5a822c00e77.png)

**Comment by mkulesh** [comment]
Released in Android version 2.9.0
Will not be merged into iOS version
