### ISSUE TITLE
[FR] Support THX audio modes

### ISSUE THREAD

**Issue by eku** [mkulesh/onpc#203]
Would it be possible to support the THX audio modes of the Onkyo TX-RZ730 in the sound profiles? That would be THX Cinema, Music and Games.

**Comment by mkulesh** [comment]
Hi @eku,
profiles are now available. Could you please install the latest debug build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.21-debug.apk and test how it works for you? Please note this APK is not signed, you may need to uninstall previous version in order to install it.

**Comment by eku** [comment]
Receiver responds with `Not available` in the AVR display.

**Comment by mkulesh** [comment]
Hi @eku,
It means your receiver does not support these THX Cinema, THX Music and THX Games modes. Please look on the "Listening mode" on the RC tab. Could you please scroll over all modes and provide me the names of modes that shall be added (exactly how they are written in this tab). If you scroll over modes please also look at the AVR display and compare names on the AVR display and on RC tab. Do you observe any differences between the AVR display and names in the RC tab?

**Comment by eku** [comment]
> It means your receiver does not support these THX Cinema, THX Music and THX Games modes.

Well. according to the RC supplied with the receiver they are called HX Cinema, THX Music and THX Games.

However, if I use `onpc` as described by you, all three modes are displayed in the APP, one time with `Dolby` and another time with `DTS`. The sequence is as follows Dolby THX Cinema, DTS THX Cinema, Dolby THX Music, etc.. The AVR does not show the prefix.

**Comment by mkulesh** [comment]
Hi @eku,
it is correct, THX Cinema and _Dolby_ THX Cinema are two different modes. AVR shows a "Dolby" symbol instead of the prefix and it is not too easy to see a full mode name on the AVR display. Now I activated Dolby THX Cinema, Dolby THX Music, Dolby THX Games:
![listening_modes](https://user-images.githubusercontent.com/30557348/102500141-486a9900-407c-11eb-9cfc-5e50de1abc1a.png)

Please install the debug build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.21-debug.apk again

**Comment by eku** [comment]
Great, that works. Is there a reason why you didn't implement the DTS THX modes right away?

**Comment by mkulesh** [comment]
Hi @eku,
Onkyo protocol declares totally 66 different listening modes. Any AVR supports only a small subset of these modes. My idea was to keep the list of modes for fast access from MEDIA tab as short as possible and only add the modes thus are really used. Do you think DTS THX modes are also useful?

**Comment by eku** [comment]
Hi @mkulesh 

Thank you for the explanation. I can understand it. The complete list can be reduced via the settings, so that the usability does not suffer and there is still no restriction.

I too have a set of profiles that I use more often. It is similar to other users. Nevertheless, it is conceivable that the sets of profiles differ, which is why I would not prune them from the start.

I may be interested in purchasing the Pro version. However, I do not have a Google account or Play services on my device. What other options are there?

**Comment by mkulesh** [comment]
Hi @eku,
If you have any Android experience, you can try to build the premium version from this repository: https://github.com/mkulesh/onpc/tree/onpc-flutter

Alternatively, I sometime upload the build here: https://github.com/mkulesh/onpc/tree/autobuild/autobuild

For example, you can try the latest build from today:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v2.9-release.apk

Currently, this is only one way to have premium version without Google account. If you like to pay for this premium build, you can just send me a donate via paypal on mikhail.kulesh@gmail.com

**Comment by mkulesh** [comment]
Released in version 2.9.0

**Comment by mkulesh** [comment]
Released in version 1.21
