### ISSUE TITLE
Add support for Pioneer VSX-923

### ISSUE THREAD

**Issue by NomisIV** [mkulesh/onpc#204]
Would it be possible to add support for Pioneer VSX-923? Since the 932 is supported, I'm guessing it *probably* shouldn't take much to support the 923 as well

**Comment by mkulesh** [comment]
Hi @NomisIV 
please take a look on this page: https://github.com/mkulesh/onpc/wiki/Support-Older-Pinoneer-Models
Do you have any Android experience and would like to help me expand the app in order to support the older Pioneer protocol?

**Comment by NomisIV** [comment]
Android development is nothing I've done before, but I'd still love to help. As I'm still just a student, with moderate experience in programming, I don't know how much I could help. I think I've got the skill for it, but not quite the experience.

You can reach me at simon@nomisiv.com, for further contact.
