### ISSUE TITLE
Prepare macOS build

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#209]
- Use right-mouse button for context menu
- Fix the margins in the landscape orientation
- Replace FlutterToast by SnackBar since Toast does not work on macOS
- Increase button paddings

**Comment by mrlad** [comment]
I see you have plans for Linux and MocOS builds.  What's the outlook for windows?

**Comment by mkulesh** [comment]
Hi @mrlad,
you are right. The macOS build is almost finished. I am looking for the testers for this macOS release. If you like to test it, just download, unzip and install the following DMG image: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v2.9.4-release.dmg.zip
The Linux build is now in progress. It works but there are some minor bugs. 
The Windows build is also planned. I will start with it after Linux version will be finished. Approximately next week. However. I cannot now estimate how long it takes since my Flutter code uses a plugin that is already ported on Android, iOS, macOS, and Linux. But I am not sure whether it ported on Windows or not. Without this plugin I am not able to build Windows version.
And some general remark. The desktop builds are based on "Flutter for desktop". This framework is not yet in stable state. Google have a roadmap that "Flutter for desktop" will be stable within 2021 but it is not guaranteed.

**Comment by mrlad** [comment]
Mac version works nicely with the DRX 5.2.  Also working well with the DTR 30.7 and DTR 40.7 over a VPN.  Great job with the port so far.

From a desktop integration standpoint, it would be nice to be able to add the app to the menu bar in settings.  Is that possible with flutter?

**Comment by mkulesh** [comment]
Hi @mrlad,
Thank you for feedback!
Unfortunately, current Flutter desktop support is not yet stable (very experimental, see https://flutter.dev/desktop). In such an unstable state it is not practicable to improve platform-dependent code like macOS menu bar. I read that there are some possibilities to do it, but I would like to wait on the stable desktop support first. 
Please note that the latest build is now available here: https://github.com/mkulesh/onpc/tree/autobuild/release

**Comment by mkulesh** [comment]
Initial macOS build is ready for testing:
![onpc-macOS](https://user-images.githubusercontent.com/30557348/107278946-b61cbb00-6a56-11eb-867d-95386e6a984a.png)

**Comment by mkulesh** [comment]
Released in version 2.10.0
