### ISSUE TITLE
Prepare Linux build

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#211]
- Create project
- Remove package_info
- Add app icon
- Fix the problem with titled edit field:
![connect](https://user-images.githubusercontent.com/30557348/106673077-626f2500-65b1-11eb-9acb-2a33dd601e6d.png)

**Comment by mrlad** [comment]
Nice!  What's your ETA for a beta or first release?

**Comment by mkulesh** [comment]
Hi @mrlad,
I am able already build it on my Fedora workstation:
![playing](https://user-images.githubusercontent.com/30557348/106965659-359f4700-6744-11eb-8444-9e5a1287fbd0.png)

@qpkorr also built it today on Ubuntu. However, there is no rpm or deb package currently. I have currently no idea how to distribute it. If you have a Linux workstation, I can prepare an instruction how to build it and you can try to build it manually. Do you have any idea that is the best way for Linux destribution? Maybe snapcraft.io for Ubuntu?

**Comment by mkulesh** [comment]
A build for Fedora workstation is available on https://github.com/mkulesh/onpc/tree/autobuild/release

**Comment by quelbs** [comment]
Checked the fedora build on Xubuntu 20.10 and it works out of the box. I just extracted the zip and was able to run the binary `Music-Control`.

The only minor thing I realized: The app icon was not used: 
![screenshot of taskbar element](https://user-images.githubusercontent.com/33117529/107340324-e9defb80-6abd-11eb-8ed8-b823eaf697fd.png)

**Comment by mkulesh** [comment]
Hi @quelbs, thank you for feedback! I changed the name of the build and updated the file on https://github.com/mkulesh/onpc/tree/autobuild/release
At the moment, I have no experience how to add the icon in the GTK runner code. I need more time to do it. If you have any experience with GTK, could you please look at https://github.com/mkulesh/onpc/blob/onpc-flutter/linux/my_application.cc and help me to add the icon?

**Comment by mkulesh** [comment]
Hi @quelbs, I hope the app icon is now fixed. In Fedora/Gnome it looks now like this:
![app_icon](https://user-images.githubusercontent.com/30557348/107800516-241af800-6d5f-11eb-86f2-24597bfbab43.png)
Please download the actual build https://github.com/mkulesh/onpc/blob/autobuild/release/MusicControl-v2.10.0-linux-x86_64.zip

**Comment by quelbs** [comment]
Thank you for fixing the icon issue. It works fine for me, now.

**Comment by mkulesh** [comment]
Released in version 2.10.0
