### ISSUE TITLE
Option to reboot device(s)

### ISSUE THREAD

**Issue by dstango** [mkulesh/onpc#225]
I'm looking for an option to reboot my Onkyo/Pioneer devices. It would be great if I could simply trigger that from the app. 

Background: when using Chromecast often devices are not showing up. Best workaround so far is to unplug the the device and then replug it again. A software solution would be much better. (Not having the chromecast issues even better ;-)...)

Thanks for considering!

**Comment by qpkorr** [comment]
I too would love the ability to power cycle my Onkyo via the app - but I'm inclined to think that sometimes I need hard power cycling, which presumably isn't possible just from software. Certainly curious what is possible though.

**Comment by mkulesh** [comment]
Hi @dstango 
unfortunately the is no command in the network protocol that allows to reboot the receiver. Please see the list of available commands in this document: https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_140.xlsx, the sheet "CMND(MAIN)"
There is a command "Reset All" available on some modern receivers, but this command may perform the factory reset of the device and it may be really dangerous to add such a command into the app.

**Comment by mkulesh** [comment]
Closed since it is not possible to implement it due to Onkyo protocol restrictions
