### ISSUE TITLE
Tunein Favorite-Links don't work

### ISSUE THREAD

**Issue by UOehler** [mkulesh/onpc#226]
I've  added  favorites from Tunin "My-Presets".
Using these favorite-links it jumps to TunIn Presets-Menu, but the music stream doesn't start.
I must push multiple times to get it working. Maybe that's an issue of the build in TuneIn-Client.

It would bi nice  to add Favorites from DAB, no Kontextmenu appears. 
Using TX-8150

Regards Uwe

**Comment by mkulesh** [comment]
Hi @UOehler
I already fixed a similar problem in the version 1.22. Which app version do you use? If the version is below 1.22, please update the app. If you already use 1.22, please collect the app log as follows:
- Open the application settings and active "Developer mode"
- Go to the SHORTCUTS tab and select your TunIn shortcut
- Open MEDIA tab and take a screenshot
- In the app menu (three dots in the top-right corner) select "latest log"
- Select whole text and send it me per email mikhail.kulesh@gmail.com with the taken screenshot. This log may help me to solve the problem.   

The favorites from DAB are already in progress, see https://github.com/mkulesh/onpc/issues/223

**Comment by mkulesh** [comment]
Hi @UOehler,
if you like to test favorites for FM/DAB, please manually download and install this APK:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.23-debug.apk
This APK is not signed. In case if any installation error happens you shall first uninstall the version downloaded from Google Play and than try to install this new APK.

**Comment by mkulesh** [comment]
Closed since information missing
