### ISSUE TITLE
TX-8130: Shortcuts don't work as expected

### ISSUE THREAD

**Issue by artzox** [mkulesh/onpc#233]
Hi Mikhail,

I really enjoyed the free version on the google playstore but missed being able to add songs to a queue so decided to get the pro version.

Using mostly DLNA on a TX-8130 onkyo receiver.

I have been trying since to get the queue to appear and be able to move songs around.
I have enabled it in the options but so far the media tab is looking the same as in the free version (meaning no icons to the right to drag) and I am not able to move anything around. Holding on a song only shows the "create shortcut" popup.

A separate issue altogether is that if I create a shortcut to a directory when I open it from the shortcuts tab I go to the main DLNA screen, meaning I see my servers.

I am attaching a screenshot of the media tab, I don't know how to show the shortcuts issue.
![173964832_500587947739912_4064693217439045241_n](https://user-images.githubusercontent.com/49994095/114982864-9f507580-9e98-11eb-84b6-a69a0ee61833.jpg)

Thanks,
S

**Comment by mkulesh** [comment]
Hi @artzox,
as I wrote by email, your receiver really does not support play queue. Based on this information, I will update the description of the app and add a new limitation:
- Following models do not support "Play Queue" feature (that is a limitation of the Onkyo firmware): CR-N765, DTR-40.5, HM76, HT-R693, HT-R695, TX-8130, TX-8150, TX-NR626, TX-NR636, TX-NR646, TX-RZ900
New description on Google Play is already submitted for both free and paid versions. On F-Droid and iOS, it will be updated with the next release. Thank you for pointing on this limitation!
The shortcut problem still be analyzed.

**Comment by mkulesh** [comment]
To be merged into free branch

**Comment by mkulesh** [comment]
Released in version 2.10.2

**Comment by mkulesh** [comment]
To be released in free version
