### ISSUE TITLE
Media Sources not refreshed after manual IP address entry

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#24]
After startup, the app connected to my local receiver.  I connected to the VPN, then manually connected to two different receivers.  The first time, the media source friendly names updated.  The second time they didn't (showed the names from the previous receiver).  I suspect this is the same issue as previously reported with switching receivers after a subnet broadcast.  But just in case it isn't, I'm opening this.

**Comment by mkulesh** [comment]
Hi @mrlad, I found and fixed one potential bug that can cause this problem. Could you please retest using the latest build?

**Comment by mkulesh** [comment]
Hi @mrlad, does this problem still be reproducible? Or it is not a problem anymore?

**Comment by mrlad** [comment]
Sorry, this was fixed in official 0.7.

**Comment by mkulesh** [comment]
Released in v0.8
