### ISSUE TITLE
Switch off all units in a group

### ISSUE THREAD

**Issue by amuth** [mkulesh/onpc#244]
A function to switch off all devices in a group would be nice.

I used the Android app. Really great

André

**Comment by mkulesh** [comment]
Hi @amuth,
thank you for the issue. I will try to add this feature within the next couple of days and will provide you a link to the test APK

**Comment by mkulesh** [comment]
Hi @amuth,

the feature is now available for testing. Please download and manually install this APK: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.24-debug.apk

It work now as follows. If you have several devices, these devices are grouped, the app is connected to the master device that is ON (the "Group/Ungroup devices" button on the LISTEN tab is highlighted), and you press "On/Standby" button from the top panel, a new dialog will appear:
<img width="810" alt="Screenshot 2021-12-08 at 23 26 47" src="https://user-images.githubusercontent.com/30557348/145300777-7bb7de9c-fe52-4607-90e5-f5ef1b1aab17.png">

If you select OK in this dialog, all known devices (currently grouped and also ungrouped) will be powered off
If you select NO, only master device will be powered off (previous behavior)
CANCEL just closes the dialog, all devices still be on.

If there are no multiroom devices found in the app, or these devices are not grouped, or the app is connected to any slave device, "On/Standby" button from the top panel works as before - no dialog appears and only this device will be powered off.

Could you please test these scenarios? Is this solution works as desired for you?

**Comment by amuth** [comment]
It worked. Thank you. Great job

**Comment by mkulesh** [comment]
Released in version 2.11.0

**Comment by mkulesh** [comment]
Released in version 1.24
