### ISSUE TITLE
Lost connection on iOS with Flutter 2.0.0 and later

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#245]
https://github.com/dart-lang/sdk/issues/47888

**Comment by Cris--** [comment]
I know iOS here but have also the problem on Android 12 with Onkyo TX-NR575E that lost the connection after a 2s successful connection.

If any log is needed plz guide me.

**Comment by mkulesh** [comment]
Hi @Cris,
I am not sure that this is the same case. Actually, I tested the app with Android 12 and the connection is stable. However, the network hardware on the Onkyo itself is not really stable. First of all, try to reset the network in your receiver: unplug the receiver from A/C and pug-in again. It shall reboot the network. Does it help? If not, which app version do you use?

**Comment by mkulesh** [comment]
Based on the symptoms this is most likely related to https://github.com/dart-lang/sdk/issues/41451 and associated fix https://github.com/dart-lang/sdk/commit/d7483c330c6d6eddced5d59b2ac2d1fd08352321, which changed socket code to try concurrent connection over IPv4 and IPv6 and choosing whatever succeeds to work-around some IPv6 connectivity issues. Though it is pretty bizarre that this would cause any sort of issues when connecting with IP addresses rather than hostnames.

Solution: Change the code to pass InternetAddress(host) instead of string host.

**Comment by Cris--** [comment]
> Hi @cris, I am not sure that this is the same case. Actually, I tested the app with Android 12 and the connection is stable. However, the network hardware on the Onkyo itself is not really stable. First of all, try to reset the network in your receiver: unplug the receiver from A/C and pug-in again. It shall reboot the network. Does it help? If not, which app version do you use?

Yep, unstable network hardware. I unplugged the Onkyo from power source and replugged after 10min. Now onpc  can communicate correctly with the Onkyo.

**Comment by mkulesh** [comment]
Released in version 2.11.2
