### ISSUE TITLE
Allow iPhone hardware volume keys to change volume

### ISSUE THREAD

**Issue by GabrielBln** [mkulesh/onpc#247]
It would be great if one could use the iPhone‘s hardware volume keys to control the Onkyo amp‘s volume.

**Comment by mkulesh** [comment]
Hi @GabrielBln 
unfortunately there is a strange Apple Developer rule. Please take a look on https://developer.apple.com/app-store/review/guidelines/#design, section "4.4.1 Keyboard extensions have some additional rules". I cite: 
They must not:
-  Repurpose keyboard buttons for other behaviors (e.g. holding down the “return” key to launch the camera).

I am just not sure whether this restriction is applied to iPhone, and, therefore, skipped this functionality in the iOS version while the Android version already supports this functionality.

**Comment by mkulesh** [comment]
Will not be fixed since this is not allowed by Apple Developer rules

**Comment by GabrielBln** [comment]
Sad to hear this, but thank you for replying!

On January 18, 2022, Mikhail Kulesh ***@***.***> wrote:
> Will not be fixed since this is not allowed by Apple Developer rules
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mkulesh/onpc/issues/247#issuecomment-1015870225>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AOBDDWHPFHEQN5NMMEXQ2T3UWXOZLANCNFSM5LAIIU2Q>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by GabrielBln** [comment]
Just found out that the iOS Sonos App does map the iPhone's volume keys
so they change the volume of Sonos devices playing music.
