### ISSUE TITLE
Shortcuts not working when an empty play queue is selected in MEDIA tab 

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#248]
The issue can be observed both in free and premium version.
HTR:
- connect to the receiver
- In the MEDIA tab, go to the Play Queue
- If Play Queue is not empty, remove all items from the queue
- Go to Shortcuts tab and select any shortcut 
*desired behavior*: shortcut is applied
*observed behavior*: shortcut is not working, nothing happens

**Comment by mkulesh** [comment]
To be merged into free branch

**Comment by 123456maniek** [comment]
Poproszę link do apk premium 2.11.1

**Comment by mkulesh** [comment]
Hi @123456maniek,
please download APK from here: https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD

**Comment by 123456maniek** [comment]
Cześć
Dzięki bardzo za apke

**Comment by mkulesh** [comment]
Released in version 1.26

**Comment by 123456maniek** [comment]
Poproszę link do apk premium 2.13.0

**Comment by mkulesh** [comment]
Hi @123456maniek, please find the latest builds here: https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD

**Comment by rn777** [comment]
> Hi @123456maniek, please find the latest builds here: https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD

It's work fine. When connected to an Onkyo TX-NR5009, there is no more delay in DLNA playback. Thank;s alot.

**Comment by 123456maniek** [comment]
Cześć. Poproszę o link do najnowszej apk premium

**Comment by 123456maniek** [comment]
Hi. How can i add to youtube playlist? Just like Spotify or Tidal

**Comment by 123456maniek** [comment]
Pioneer 932

**Comment by 123456maniek** [comment]
Można już pobrać apkę 2.13.1
Można dodać do listy YouTube Music?

**Comment by mkulesh** [comment]
Hi @123456maniek,
I uploaded new version on this page: https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD

Does the official Onkyo app show YouTube Music on the NET service list for your model? If not, it will be not possible. If yes, could you please send me a screenshot of the official app where YouTube Music is listed?

**Comment by 123456maniek** [comment]
Niestety oficjalna aplikacja nie pokazuje YouTube Music. Szkoda, że nie da się nic zrobić.

**Comment by mkulesh** [comment]
Hi @123456maniek 
Unfortunately no chance for YouTube Music since the streaming functionality is implemented in the receiver firmware. I have no possibility for any workarounds within the app. 

Following  ways only are possible:
- if your receiver supports Bluetooth input: you can play YouTube Music on your smartphone and stream it to the receiver via Bluetooth.
- if you have an iOS device and your receiver supports AirPlay: play YouTube Music on iOS device and stream it to the receiver via AirPlay.
- if you use a desktop and your receiver supports Chromecast: install any Chromecast client on desktop and stream YouTube Music from desktop to the receiver via Chromecast.
