### ISSUE TITLE
Supported device list

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#26]
Onkyo arbitrarily limit which of their apps work on various receiver models (i.e. the controller app only works on the newer Integra/Onkyo receivers, while the older receivers only work with the Integra/Onkyo Remote app).  The protocol seems relatively device agnostic and your app works on both the 30.7/40.7 and DRT 5.2 which I've tested.  So this seems to be a big selling point for the app.  Much wider compatibility potential.

It would be nice if you had a user generated and/or automated list of devices onpc is known to work with.  This could be done one of two ways:

1. Have the user send you a report (via a button or something similar)
2. Add an Android permission to auto-report the info.

I know you want as few permissions required as possible, but throwing potential options out there. 

This info  then could be placed in the program feature list and/or the device settings page.

**Comment by mkulesh** [comment]
Hi @mrlad, you are right. On the one hand, I can add new item "Feedabck" in the Navigation Drawer. In the dialog show you summary (like Onkyo arbitrarily limit which of their apps work on various receiver models (i.e. the controller app only works on the newer Integra/Onkyo receivers, while the older receivers only work with the Integra/Onkyo Remote app). The protocol seems relatively device agnostic and this app should work with all devices. Please let us known how the app supports your device). Provide 3-4 options like "All features work", "There are minor bugs", "Nothing works". Provide an edit field for some comments and button "Submit via Emal". This button will just call the standard Emal program with pre-filled mail text.

On the other hand, I have troubles to promote the app. I was able only post on reddit (https://www.reddit.com/r/Onkyo/comments/a6ohqu/alternative_onkyo_controller_app_for_android) and on AVS forums (the post that you replied). I also submitted today the app to F-Droid and plan post about the app on reddid (r/fossdroid) after it will be accepted.

 However it is not enough... Could you maybe post something on AVS forum after we add this  "Feedabck" option?

**Comment by mrlad** [comment]
I will be happy to help promote on AVS and social media.  However, I previously had a Denon receiver and at least with Denon users, most official threads have a section on the apps available.  We need to figure out how to get your app listed on the Onkyo official receiver threads on AVS.  Unfortunately, none of the Onkyo AVS threads I've seen have this info.

**Comment by mrlad** [comment]
Do you have an XDA Forums account?  That's another good site to publicize the app.  Lots of android developers there.

**Comment by mrlad** [comment]
FYI...I noticed in the Integra Remote Controller app that it lists the bugs that can be encountered with each model year (starting with 2009 and I think ending with 2013).  Would you like to see a screen cap?

**Comment by mkulesh** [comment]
Hi @mrlad,

> bugs that can be encountered with each model year (starting with 2009 and I think ending with 2013). Would you like to see a screen cap?

Yes, it is interesting information. Is there any possibility to extract this list as a text in order to push it in the doc directory of this project? 

> Do you have an XDA Forums account? That's another good site to publicize the app. Lots of android developers there.

Not yet. I have an account on 4pda.ru that is russian alternative to XDA Forum and will publish the app on 4pda this week. I also wait for the inclusion of the app on F-Droid and after it will post on reddit. 

> I will be happy to help promote on AVS and social media. However, I previously had a Denon receiver and at least with Denon users, most official threads have a section on the apps available. We need to figure out how to get your app listed on the Onkyo official receiver threads on AVS. Unfortunately, none of the Onkyo AVS threads I've seen have this info.

Alternatively, we can post in "Community Articles ": https://www.avsforum.com/forum/308-community-articles
That do you think about it?

**Comment by mrlad** [comment]
Here's the list of issues in the app

2009 models
	* Operation via iRadio and Server Selector is unavailable
	* 
Music streaming from Android/iPhone/iPod/iPad is unavailable
	* 
Network Standby function on your device must be set to ON
	* 
External operation via CEC using app is unavailable

2010 models
	* 
Operation via iRado and Server Selector are only available using cursor keys
	* 
Network Standby function on your device must be set to ON
	* 
External operation via CEC using app is unavailable

2011 models
	* 
Please select Page Switch button for NET Selector. Operation per individual screen is available only
	* 
Network Standby function on your device must be set to ON

2012 models or later
	* 
Some devices do not support Network Standby function. Please turn your device on manually

**Comment by mkulesh** [comment]
Hi @mrlad, thanks, I added this list to the documentation directory:
https://github.com/mkulesh/onpc/blob/master/doc/known_integra_bugs.md

**Comment by mrlad** [comment]
@mkulesh IDK about the copyright of the text.  You may need to change the wording up a bit to prevent any copyright concerns.

**Comment by mkulesh** [comment]
The supported device list is added in README on project page based on Google Play reviews and issue list.
