### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [mkulesh/onpc#273]
https://monitor.f-droid.org/builds/log/com.mkulesh.onpc/41#site-footer

This is a known issue. Could you please update the AGP to a version higher than 4.2? Thanks!

**Comment by linsui** [comment]
Please also move the short_description files in https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata/com.mkulesh.onpc into your repo. Thanks!

**Comment by mkulesh** [comment]
Released in version 1.29
