### ISSUE TITLE
Lock Screen Notification for the App

### ISSUE THREAD

**Issue by nick16** [mkulesh/onpc#286]
I would like to be able to control my receivers volume without having to unlock my phone (as well as change the media source).

Just like I can skip the next song in a music apps lock screen notification, I would like to change the volume of my receiver through this app in the lock screen.

**Comment by mkulesh** [comment]
Hi @nick16,
thank you for the issue. Which app version do you mean - Android or iOS? At the moment I am not too familiar with the lock screen API, but will take a look on this.

**Comment by nick16** [comment]
I am using the Android version from F-Droid.

**Comment by nick16** [comment]
This enhancement appears to be added (at least a sufficient alternative) in the latest version 1.32.
Therefore, this ticket can be closed.

**Comment by mkulesh** [comment]
The app can now be started on the lock screen (Allow to run the app on the top of the lock screen #302) that solves the problem in an alternative way.
