### ISSUE TITLE
No tasker integration 

### ISSUE THREAD

**Issue by LouKingGood** [mkulesh/onpc#288]
I don't see this in the tasker plugin

**Comment by qpkorr** [comment]
There's no Tasker plugin as far as I know, but you can user Tasker to send "intents" to onpc. Lots more here https://github.com/mkulesh/onpc/issues/184

**Comment by qpkorr** [comment]
Ah - I just found where the documentation for Tasker went - https://github.com/mkulesh/onpc/tree/master/doc/Tasker
It's clearly not as user friendly as a dedicated plugin (which nobody has had the time/interest/ability to write yet) - but it has certainly worked for me.  

However - it seems Google has pulled it's usual trick of stopping things working which are good - and the voice control mechanism described there using Tasker's "AutoVoice" plugin no longer works: https://www.reddit.com/r/tasker/comments/149wqo0/psa_you_can_no_longer_use_autovoice_with_google/
I'm investigating alternatives (eg using ChatGPT as the Tasker dev suggests) but I don't promise any useful results

**Comment by mkulesh** [comment]
Hi @LouKingGood
As answered above, the Tasker integration is implemented using intents. I have no plans to implement any plugins by myself, but I appreciate any contributions to the project. If you are able to  implement such a plugin, please feel free to submit a pull request.
