### ISSUE TITLE
Shortcuts with some special symbols in the name are not shown in the widget

### ISSUE THREAD

**Issue by Squirell1** [mkulesh/onpc#299]
Fo I have to expect any reaction by pressing the refresh icon on 2x2 widget?
How to add more entries? 
Changed favorites already with no reaction.

**Comment by mkulesh** [comment]
Hi @Squirell1 
if some new shortcuts are added in the app in the SHORTCUT tab, or some shortcuts renamed/deleted, the widget shall be updated automatically. However, I observed (really rarely) that such an automatic update not happens. The refresh button shall help in this case, i.e it synchronizes the list of shortcuts between the widget and the app, if it not synchronized automatically. Do you change the shortcuts list in the app and this refresh button has no effect in order to update it in the widget?

**Comment by Squirell1** [comment]
Yes. That's what I did and observed. 
Refresh does not fetch the changes

**Comment by Squirell1** [comment]
Hi @mkulesh 
thanks for further information. 
I did some more investigation and noticed that seen behavior occurs only for favorites set by TuneIn radio stations. 
Favorites out of FM/DAB seems to be fine.

**Comment by Squirell1** [comment]
Very strange - TuneIn station SWR3 gets the issue. E.g SWR1 is doing fine

**Comment by Squirell1** [comment]
Also, YouFM faces the issue. Maybe there is something in the cache not deleted.

Is there a way to export the general settings of the app? So I'd try to reinstall it and create favorites again.
Maybe I can delete a specific file on the smartphone containing the favorites for reset.

**Comment by mkulesh** [comment]
Shortcuts with some special symbols like "$" in the name are not shown in the wigdet.
How to reproduce:
- Create a shortcut for the following TuneIn Station: By Location->Europe->Germany->Würzburg->Antenna Baden-Württemberg (Top 40 & Pop Music)
- Ensure that the shortcut appears in the SHORTCUTS tab
- Close the app and add shortcut widget. If the widget alreadz exists, press "Refresh" button in top-right corner of the widget
_Expected result_: new shortcut appears in the widget
_Observed result_: shortcut is missing

**Comment by mkulesh** [comment]
Hi @Squirell1, 

thank you for details. Now I am able to reproduce and fix the problem.

Please find new build here: https://1drv.ms/u/s!At2sh2-YDyGFg0CYHVUa907vPaQW?e=pkhE6u

Unfortunately, it will be necessary to recreate the shortcuts that are missing in the widget. The shortcuts already shown in the widget can still unchanged.

**Comment by Squirell1** [comment]
Hello @mkulesh 
Thanks a lot for fixing the issue and providing a new sw version. 
Now the problem is solved 👌.
You just have to rearrange the order of one entry in the favorite list to trigger the refresh in the widget list. The widget is updated and shows all missed items.

**Comment by mkulesh** [comment]
Released in version  2.13.3
