### ISSUE TITLE
App Battery Usage

### ISSUE THREAD

**Issue by nick16** [mkulesh/onpc#309]
This app tends to drain battery quickly. I have the setting 'Keep the screen turned on' enabled. After leaving the app running for 5 minutes, my phone tends to get warm, and the battery depreciates quickly. Why does this app use so much battery? Can it be optimized?

My Device:
Pixel 6a
Graphene OS
No Google Play Services installed.
I am using the Music Controller app from the F-Droid app store.
I am connecting to my Denon AVR

App settings:
'Keep the screen turned on' enabled
'Volume keys turning' enabled

**Comment by nick16** [comment]
I've been using version 1.31.
I downloaded version 1.32 and will record if the battery usage is any different.

**Comment by nick16** [comment]
I notice when the app is running in the lock screen, my phone does not heat up and the battery doesn't drain.
I'm going to close my ticket since I am not seeing this issue after updating to 1.32

**Comment by mkulesh** [comment]
Hi @nick16,
I have never previously observed such a behavior. If you observe a huge battery drain again, please reopen this issue, it shall be analyzed.
