### ISSUE TITLE
Display of Input Selectors While in Standby

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#31]
For the first time, I started up onpc while both the main and zone 2 were in standby.  I found the display of the input selectors (i.e. media sources) confusing.  The list was empty.  I thought the app was broken and then a few minutes later, I figured out that they aren't shown when the device is in standby.  It would be better if that tab were disabled/grayed out if the device is in standby.

**Comment by mkulesh** [comment]
Hi @mrlad, done, see attached screenshot. You can test it in the newly created version 0.9:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.9-debug.apk

![input_selectors](https://user-images.githubusercontent.com/30557348/53762774-4ba58c80-3ec9-11e9-85fc-d10b7d34196b.png)

**Comment by mrlad** [comment]
It does work, but if you're on the Media tab, the input sources don't change color when the device goes into standby or comes out of standby.  If you switch away and then back to the media tab, they are painted with the correct  color.

I also wonder if the color should be the same color as the power button for consistency?  Unsure, I do like the lighter gray color though.

**Comment by mkulesh** [comment]
Hi @mrlad, unfortunately, different ONKYO devices have different sequence of messages on switching device on. Therefore, it worked on my player and does not work on your receiver. I now tried to process this initial message sequence more generally and hope it will now also work for your device. Please test.

**Comment by mrlad** [comment]
This seems to properly detect going in/out of standby.

One other suggestion for this feature.  Several of the other receiver apps I've tested show a power button in the middle of the screen when the device is in standby (the official Integra app does this also).  Is this something you can consider as another visual indicator?

**Comment by mkulesh** [comment]
Hi @mrlad, I am not sure about this addition button since It is not really consistent with current design. But that do you think about the following solution:
- Add new setting "Switch on remote device on connect". By default false.
- If app is started and detects that the remote device is in stand-by, and this setting is on, the app automatically switches the device on.

**Comment by mrlad** [comment]
I like your proposal @mkulesh .  Will it switch all zones to on or will there be an auto-on setting for each zone?

**Comment by mkulesh** [comment]
Hi @mrlad, ok, I created new issue #38 for this setting

**Comment by mkulesh** [comment]
Released in version 0.9
