### ISSUE TITLE
Display input/output channels and codecs for Denon

### ISSUE THREAD

**Issue by DarkSkyGhost** [mkulesh/onpc#321]
In official Denon app there is ability to see the input and output channels with additional info about input codecs.

Can this be shown in onpc too?

![Screenshot_20240922_113834_Denon AVR Remote](https://github.com/user-attachments/assets/a7396f44-45ee-4419-9316-7ad906d1d7c6)
![Screenshot_20240922_113848_Denon AVR Remote](https://github.com/user-attachments/assets/a9535e19-ed9a-432f-9694-05774f715543)
![Screenshot_20240922_113857_Denon AVR Remote](https://github.com/user-attachments/assets/2a816a8a-a4ed-44f2-815f-689002e264e9)
![Screenshot_20240922_113910_Denon AVR Remote](https://github.com/user-attachments/assets/9fcdefcd-0962-4d6f-a40d-43150fba307f)

**Comment by mkulesh** [comment]
Hi @DarkSkyGhost,
this behavior is not documented in the Denon Communication Protocol description, but I will take a look and try to reverse it.

**Comment by mkulesh** [comment]
Hi @DarkSkyGhost,

I finalized the initial implementation for AV info.  Now, "Audio/Video info" button is available in the LISTEN tab:
![Screenshot from 2024-09-29 11-46-03](https://github.com/user-attachments/assets/b41633d3-132f-4a3c-83f6-6667ee14ce6f)

When you press the button, the "Audio/Video info" window appears where available information will be shown:
![Screenshot from 2024-09-29 11-49-01](https://github.com/user-attachments/assets/a9f53d7c-b014-4f57-9187-3214161eeb52)

Could you please test how it works for you?

Please download the manually install MusicControl-v2.14.1-android.apk from here:
https://1drv.ms/f/s!At2sh2-YDyGFdsDFl6N3ncDowMg

**Comment by DarkSkyGhost** [comment]
I've installed the app, but unable to connect to Denon. Weird.

When trying to access Denon in web control through IP and opening HEOS Account page, it returns HTTP 500.

Maybe you have any idea what's happening? It's probably not related to onpc.

I've tried rebooting the AVR, but didn't help.

**Comment by mkulesh** [comment]
Hi @DarkSkyGhost,
my AVR also freezes some time. In my case, a disconnection from AC power and connection to AC power again helps. Disconnection from AC power is necessary in order to reboot network module that is always, also in standby mode, active.

**Comment by DarkSkyGhost** [comment]
Sorry, deleted the comment.

Seems that Roon/RHEOS somehow breaks connection to onpc.
After turning off Roon and restarting Denon, it starts working. But as soon as Roon is launched, it breaks again.

So, regarding the feature:

Works nice, shows input codec and quality correctly :)

**Comment by mkulesh** [comment]
Released in version 2.14.1
For premium version only
