### ISSUE TITLE
Balance slider together with volume

### ISSUE THREAD

**Issue by TonyCrawford** [mkulesh/onpc#324]
Hi Mikhail!

Since you asked for suggestions: what would be nice for me, since I have two favorite chairs in my living room, would be a balance slider right alongside the main volume control.

(Among the many many defects of the Denon app is that the balance is poorly accessible there too: you have to click through layers of slow animated screens to get to the balance control.)

(IIRC, looking at the protocol spec, balance seems to have been an afterthought there too: it was way down the list of commands.)

**Comment by mkulesh** [comment]
Hi @TonyCrawford

I finalized the initial implementation of the balance function. Please note this this function is only available for the Denon STEREO receivers like DRA-800H and not available for any 5- or 7-channels receivers.

Now, the balance slider shall be available in the "Audio Control" window:
![Screenshot from 2024-10-04 12-49-27](https://github.com/user-attachments/assets/4b257035-300e-4dd9-a634-c068ca24432c)

Could you please test how it works for you?

Please download the manually install MusicControl-v2.14.1-android.apk from here:
https://1drv.ms/f/s!At2sh2-YDyGFdsDFl6N3ncDowMg

**Comment by mkulesh** [comment]
Released in version 2.14.1
For premium version only
