### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#33]
https://gitlab.com/fdroid/rfp/issues/905
https://search.f-droid.org/?q=mkulesh&lang=en

**Comment by avuton** [comment]
This is complete. Just installed for the first time after finding on F-Droid. Amazing so far. Thanks!

**Comment by mkulesh** [comment]
Hi @avuton, thanks! If you have any ideas how to improve the app please submit an issue.

**Comment by licaon-kter** [comment]
Umm, we have [AutoUpdate in F-Droid](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mkulesh.onpc.yml#L116), but you modify versionName when you start developing (eg. `1.9`), which is fine, but... when you're done you Tag `v1.9` but by now versionName is already `1.9.2` so when F-Droid's checkupdate script does the pull [it will think versionName and Tag should be the same](https://f-droid.org/en/docs/Build_Metadata_Reference/#AutoUpdateMode)... and there's no Tag `v1.9.2` so it fails to build the app.

Some ideas:
* Tag 1.9 but keep versionName 1.9
* Update versionName to 1.9.2 but Tag 1.9.2

Thoughts?

**Comment by mkulesh** [comment]
Hi @licaon-kter,
thank you for observation. You are right. Unfortunately, I labeled this release wrongly. Now, I changed the tag name (and release name) from 1.9 to 1.9.2. Will be AutoUpdate on F-Droid triggered automatically or shall I do something else manually?

**Comment by licaon-kter** [comment]
I've fixed current version (but maybe now it's out of sync :)), this was noted for the future.

**Comment by licaon-kter** [comment]
Yes...there's a 1.9.2 tag...but... https://github.com/mkulesh/onpc/blob/v1.9.2/app/build.gradle it's not for version 1.9.2

See my post above...again @mkulesh

**Comment by mkulesh** [comment]
Yes, you are right, I have already started to work on the new version. Therefore, the trunk build.gradle  points to new one (1.10) since I was sure that F-Droid builds from branch tag but not from trunk. Is it not the case? I suggest to reduce effort related to this problem. I plan to release 1.10 in one or two weeks. I will keep this problem in mind and perform the release correctly and the problem will be automatically solved. That do you think?

**Comment by licaon-kter** [comment]
@mkulesh pretty please click the link... If that's tag 1.9.2 it doesn't point to the right commit then, as that commit says 1.10...

**Comment by mkulesh** [comment]
Thanks, I see the problem now. When I edited the tag name, github moved this tag to the actual state (i.e the commit that was not in the tag previously). The attached source tarball (https://github.com/mkulesh/onpc/archive/v1.9.2.zip) also contains a wrong state. For me, it is strange behavior of github that actually does not allow to edit wrongly given tag name. Unfortunately I am not too familiar with git and do not see any solution for this problem. Do you know, is it now possible to create now a tag with a desired name (1.9.2) from this commit: https://github.com/mkulesh/onpc/commit/b8c9123030a1ed5a0e09fb595bdcedb1bb747630?

**Comment by licaon-kter** [comment]
Afaik, you can tag whatever version to whatever commit, but I can't help you. :)

**Comment by mkulesh** [comment]
No problem, I will than release new version and make a correct tag soon. Let us just wait until new release.
