### ISSUE TITLE
Allow nightly build to co-exist with the Play Store Version

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#34]
It would be useful for comparison purposes to have both the nightly build and the Play store version on the same device.  It also is frustrating having to uninstall before every nightly build and lose all my settings.  I know some other apps that I beta test are able to do this, but I'm not sure of the exact mechanism.

**Comment by mkulesh** [comment]
Hi @mrlad, if these apps are available on github, could you please provide me the links to the repository?

**Comment by mrlad** [comment]
Sorry, not on github.  Closed source.

**Comment by quelbs** [comment]
As far as I know the apps need to have a different **applicationId**, because this is the only identifier for distinguishing apps. But I don't know how easy it is to build a debug app with a different appId.

**Comment by mkulesh** [comment]
I think this problem is not more important since the app is stable and there are not too much developer build.
