### ISSUE TITLE
Missed network services

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#35]
On some receivers, the following network services are missed in the MEDIA tab, but are visible in the "Network Services" settings
- USB/USB(Front)
- USB(Rear)
- DTS Play-Fi

![screenshot_2019-03-06-17-19-26-791](https://user-images.githubusercontent.com/30557348/53913726-49c00280-405c-11e9-8a0a-0d3c4061a9aa.jpeg)

![screenshot_2019-03-06-17-20-15-653](https://user-images.githubusercontent.com/30557348/53913728-49c00280-405c-11e9-899f-bf8ce53e8500.jpeg)

**Comment by quelbs** [comment]
I have a similar issue, for me "Rear USB" is displayed in the "Media" list, but there is only a front USB available on my device (TX-8150). If I select it, there is USB/items:1 and an hourglass, but the device itself is not listed. After "selecting" it by RC > dotted circle, I see the folder list in the NET tab.

**Comment by mkulesh** [comment]
Hi @quelbs, I already tried to fix it and hope it can work now. Could you please install and test the latest automatic build from here:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.9-debug.apk

This build also contains your German translation. Since the build is not signed, you may need to uninstall previous apk version before installing this build.

**Comment by quelbs** [comment]
It now correctly displays Front USB, but the device itself is not listed. After selecting it in RC section the folders are shown again.

**Comment by mkulesh** [comment]
Since I have an other model where both USBs are presented in the device selector list (not in network services) I am unable to debug it. Are you able to record and send me per e-mail the log file, where:
- receiver is initially in stand-by
- start the app and switch on the receiver
- select MEDIA tab
- select Network services
- select USB in the app
- after it select USB in RC
- close the app

Debug mode is activated in the automatic build.  The simplest way to collect log is described here:
https://github.com/mkulesh/onpc/wiki/Collect-Logs

The communication log between the app and Onkyo device may contain information (like Onkyo device ID) that shall not be published in Internet. Do not attach this log here!

**Comment by mkulesh** [comment]
Hi @mrlad, could you please check how the USB presented in network services works on your device(s)?

**Comment by quelbs** [comment]
I just sent the log file. Thank you in advance for having a look into it. If I can assist any further, let me know.

**Comment by mrlad** [comment]
Play Fi and Front USB show up in Network services but not the Media tab.

**Comment by mrlad** [comment]
PlayFi is really buggy for me so I don't use it (that and it can't stream to Zone 2 which basically makes it worthless for me).  That's why I didn't notice this.

**Comment by mrlad** [comment]
I downloaded the latest autobuild and it fixed the problem for me.

**Comment by quelbs** [comment]
Thank you for fixing the USB selection also for TX-8150. Works with single partition sticks as well as with multiple partitions now.

**Comment by mkulesh** [comment]
Released in version 0.9
