### ISSUE TITLE
Switch-on remote device on app startup

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#38]
Introduce new configurable parameter that allows to switch-on remote device on app startup

**Comment by mkulesh** [comment]
Hi @mrlad, the new setting is implemented. This setting only impact the current zone; i.e if you changes the zone in the navigation drawer, and this target zone is in stand-by, it will be switched on.

![auto_power](https://user-images.githubusercontent.com/30557348/53992073-3bd9b280-412c-11e9-80a1-761d1cf3b236.png)

**Comment by mrlad** [comment]
The new settings works nicely for me (both Main and Zone 2)

**Comment by mkulesh** [comment]
Released in version 0.9
