### ISSUE TITLE
Additional language setting "Use system language"

### ISSUE THREAD

**Issue by quelbs** [mkulesh/onpc#39]
After a clean install the system language of the device is taken (if it is available), but when changing a setting (like theme) the language switches to English (probably because this is the first language in the list). There should be an additional setting "System language (if available)". That also would allow to use the language instead of English when it becomes available.

**Comment by mkulesh** [comment]
Hi @quelbs, it was easy. Please test.

**Comment by quelbs** [comment]
Works fine, thank you for fixing it.

**Comment by mkulesh** [comment]
Released in version 0.9
