### ISSUE TITLE
Toggle repeat modes

### ISSUE THREAD

**Issue by quelbs** [mkulesh/onpc#41]
There are multiple repeat modes (repeat-1, repeat-all, repeat-folder, no-repeat) are they available? I do not see which one is active/can be selected in the App.

**Comment by mkulesh** [comment]
Hi @quelbs,

thank you for pointing to this problem. Yes, there are different repeat modes, I just used the same icon for all these modes. Now, all modes you mentioned have own icon. Please test.

**Comment by quelbs** [comment]
Great, works for me with current debug version!

**Comment by quelbs** [comment]
Released in version 0.9
