### ISSUE TITLE
Pioneer not auto discovered

### ISSUE THREAD

**Issue by edent** [mkulesh/onpc#46]
Love this app - just what I needed.

I have a Pioneer amp (made by Onkyo). The app doesn't find it when searching the network. If I manually put in the IP address it connects fine and I can use the app to control my amp.

Is there any info I can give you to make the discovery process work?

**Comment by mkulesh** [comment]
Hi @edent, are you able to collect the application log as described here: https://github.com/mkulesh/onpc/wiki/Collect-Logs? If yes, it would be a good start point. Please do not publish the log file here, just send it me per email. The idea behind the search is that the app sends an UDP broadcast in the local network, and remote devices shall answer with a [Broadcast Response Message](https://github.com/mkulesh/onpc/blob/master/app/src/main/java/com/mkulesh/onpc/iscp/messages/BroadcastResponseMsg.java). It looks like Pioneer ether do not answers with this message, or this answers has a slightly different format. The logging can help to understand it.

**Comment by mkulesh** [comment]
No feedback

**Comment by mkulesh** [comment]
Hi @edent, I fixed the problem and the actual nightly build is able to discover Pioneer device. Could you please test it?

**Comment by edent** [comment]
Oh! Brilliant! I'm away from home at the moment, but I will be able to test it at the end of the month. Thank you 😊

**Comment by mkulesh** [comment]
Released in version 1.3

**Comment by edent** [comment]
Works perfectly! Thanks :-)
