### ISSUE TITLE
NET/TI stream stops playing when opening the app

### ISSUE THREAD

**Issue by quelbs** [mkulesh/onpc#51]
When opening the app and a NET/TI stream is playing the playback stops.

TX-8150 - log via mail.

**Comment by mkulesh** [comment]
Hi @quelbs,

thank for the logging. I believe I found the problem. Any Onkyo receiver has two modes: list mode and playback mode. If you toggles between track cover and the media list in the official Onkyo app, the app also toggles the mode on the receivers. And vice versa, if the receivers changes the mode, the app automatically toggles the view. In my app, I try to develop other interface where
botch modes co-exists. Some time it is not comfortable (for example if playback is started, the receiver mode is playback and the media list is empty). Therefore, I automatically switch the mode
to the list mode on some events. It seems to be that some receivers do not accept such a mode change for TuneIn service and stops the playback. Now, I disabled the mode change for TuneIn.
I think it shall solve the problem. As a result, if you starts the TuneIn (directly or from "my Favorites") the receiver shall still be in playback mode and you will see "Playback mode" indication on the
MEDIA tab. Could you please test the latest autobuild?

**Comment by mkulesh** [comment]
Released in version 1.0
