### ISSUE TITLE
Change bass, center, treble and subwoofer levels

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#60]
Add the ability to change bass, center, treble and subwoofer levels. That is something which is missing. Currently, the App reacts on the level change as follows:

Changing center from +2 to +1 to 0 gives this logging:
#0427: MessageChannel: << new message CTL, size=26B, remaining=0B
#0428: MessageChannel: << error: ignored: No factory method for message CTL: ISCP/v1[16,10]: CTL(+1)
#0429: MessageChannel: << new message CTL, size=26B, remaining=0B
#0430: MessageChannel: << error: ignored: No factory method for message CTL: ISCP/v1[16,10]: CTL(00)

Changing subwoofer from +1 to +2 to +3 gives this logging:
#0639: MessageChannel: << new message SWL, size=26B, remaining=0B
#0640: MessageChannel: << error: ignored: No factory method for message SWL: ISCP/v1[16,10]: SWL(+2)
#0641: MessageChannel: << new message SWL, size=26B, remaining=0B
#0642: MessageChannel: << error: ignored: No factory method for message SWL: ISCP/v1[16,10]: SWL(+3)

**Comment by mkulesh** [comment]
Added bass and treble:
![audio_control](https://user-images.githubusercontent.com/30557348/59302143-92a6d900-8c93-11e9-9457-fd69836746f2.png)

**Comment by mkulesh** [comment]
Added Bass, Treble, Subwoofer level, Center level
![audio_control](https://user-images.githubusercontent.com/30557348/59537897-4c05e880-8ef8-11e9-9c54-38b9b7de8e5d.png)

**Comment by quelbs** [comment]
Thank you for adding this feature! I just found some time testing is. One thing I realized: you seem to check if changing works and disable the feature of it does not work, but this should be saved for each preset. On my receiver you can only change the values in stereo mode, but it is also displayed in the other modes. After trying to change in direct mode it is also hidden in stereo mode (until app refresh).

**Comment by mkulesh** [comment]
Hi @quelbs, you are right, I show the slider if the receiver answers the level query for this value before the dialog is opened. The problem is that the  ReceiverInformation does not provide any relationship between listening mode and availability of tone control. Do you have any idea how which condition can be used in order to disable tone control for given mode?

**Comment by quelbs** [comment]
One thing would be to curate a list of listening modes and corresponding availability. E.g. "Direct" and "Pure audio" mode sound like they never allow changing the levels. I think this is valid for all devices. As I only have "Stereo" and those two on my receiver, I can only help with these three presets.

An alternative would be to have an "check possibilities" option where the app tries all modes and saves the findings (if the mode is available and if it allows the control of bass, etc) in the app settings.

**Comment by mkulesh** [comment]
HI @quelbs, thank you for idea. Now, I expanded ListeningModeMsg by new boolean parameter that defines whether the tone control shall be disabled for this mode. Could you please test?

**Comment by quelbs** [comment]
Works fine for me, thank you for implementing it.

**Comment by mkulesh** [comment]
Release in v1.2
