### ISSUE TITLE
Allow add to the Play Queue from a DLNA server 

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#63]

**Comment by mkulesh** [comment]
Context menu for DLNA service is now allowed:
![context_menu_for_dlna](https://user-images.githubusercontent.com/30557348/57957182-ba588a80-78fb-11e9-9a55-6c3761fd4da3.png)

**Comment by qpkorr** [comment]
Ha - nice email response Mikhail! And whilst your screen shot shows the context menu on a file, I presume you're making it work on directories too?
Cheers!
John

**Comment by qpkorr** [comment]
For the benefit of anyone else, I'll answer this question myself - yes, the fix does indeed work recursively on directories too.

**Comment by mkulesh** [comment]
Released in version 1.1
