### ISSUE TITLE
Onkyo TX-NR636

### ISSUE THREAD

**Issue by christian-fischer** [mkulesh/onpc#78]
Just stumbled upon your app in F-Droid and tried it with my [Onkyo TX-NR636](https://www.eu.onkyo.com/en/products/tx-nr636-98893.html) and I can report that it works great! First off, a big thank you for your effort in creating this app! It's way better than the official onkyo app.

The only minor thing that I noticed, that's not working, is the time seek while in NET or USB playback mode.
The ISCP specification mentions something that this command only works when time seek is enabled, so I'm not sure if my configuration is at fault - but I haven't found any indication where I could enable this?

Let me also share my [receiver-information.txt](https://github.com/mkulesh/onpc/files/3390158/receiver-information.txt) for this device.

**Comment by mkulesh** [comment]
Hi, sorry for a late response and thank you for submitting issue. You are right, time seek is only enabled if the receiver allows it using "NMS" message. This message is always sent at the playback start. For my player, time seek is always enabled for USB playback and for some NET services like Play Queue. For network streaming services like Deezer or TuneIn radio, the time seek is always disabled. 

The app has already a mechanism that allows to collect logging. Could you please provide me the application logging from a debug version of the app installed from here: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v1.2-debug.apk

In this version of the app, open application settings and activate "Developer options". An application menu appears on the right of the toolbar. This menu contains the option "Latest logging". 

Start playing any song from USB where you expect time seek shall be enabled. After it, select this menu "Latest logging", than select all text from the logging dialog and send it me per e-mail with a screenshot of the  

I can than inspect why the time seek is disabled for your device.

**Comment by mkulesh** [comment]
No responce
