### ISSUE TITLE
TX-8050 no net Item list

### ISSUE THREAD

**Issue by ArtemiisFowl** [mkulesh/onpc#87]
Hello,

thanks for this app.
My TX8050 works well with one problem:
In Net-menu (or usb) the acc does not show any items to click on. It just says (f.e.): NET | Elements: 7 and a sandwatch...

Is this not possible with my older device?

**Comment by mkulesh** [comment]
Hi, thank you for feedback! Could you please collect a log as described in https://github.com/mkulesh/onpc/wiki/Collect-Logs and send me it per e-mail on mikhail.kulesh@gmail.com together with a screenshot on the MEDIA tab?

**Comment by mkulesh** [comment]
No feedback, a fix without requested log is not possible.

**Comment by ArtemiisFowl** [comment]
Sorry for my late answer.
I send you the logcat output and the screenshot per mail.

**Comment by mkulesh** [comment]
Released in v.1.8
