### ISSUE TITLE
iOS build for version 2.0

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#91]
Prepare iOS build for version 2.0

**Comment by mrlad** [comment]
Is there an iOS release available on TestFlight or is it still in development?

**Comment by mkulesh** [comment]
It already works really good on my iPad, but there are currently no official build. If you have a Mac and XCode installed, you can try to build it manually from this branch: https://github.com/mkulesh/onpc/tree/onpc-flutter

**Comment by mrlad** [comment]
Don't have easy access to XCode right now.  I'll wait for an official build.  But I'm **very** glad to know this is coming!

**Comment by mkulesh** [comment]
Actually, I ported the app to the new Google framework called Flutter. The same code works in both Android and iOS. Theoretically, it is also possible to build this code for a desktop (Windows, macOS), but I not yet tried it. The latest build for Android from this common code tree is https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v2.0-release.apk  
If you like to test this new experimental version on Android, just install this APK. This new version shall import all app settings from the previous version.

**Comment by mrlad** [comment]
I'm very much interested in a desktop app too once the iOS release happens.  Do you have a target ETA for public testing in TestFlight?

**Comment by mkulesh** [comment]
Hi @mrlad,
the first build for iPhone and iPad is now available on TestFlight and I sent you invitation to test it per email.

**Comment by mrlad** [comment]
This build is in excellent condition!  Was surprised to see that Flutter enabled the app to be a full iPad app. 

I tested on an iPad Pro running iOS 13..2.3 with a DRX 5.2 and 30.7 and 40.7.  Only encountered one minor bug with the friendly name not being shown for the media input

**Comment by mrlad** [comment]
I also tested changing settings/volume on Android and watching the corresponding setting change on iOS (and visa versa).

**Comment by mkulesh** [comment]
Released in version 2.0.3 (iOS)
