### ISSUE TITLE
NAS items are missing on NT-503

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#92]
On NT-503, samba servers are missing in the HomeMedia folder

**Comment by Jay000000** [comment]
The same bug also seems to affect the CR-N765. Possibly due to the device constantly refreshing the available servers?

![Screenshot_20191116-100807](https://user-images.githubusercontent.com/57828742/68990910-2be8a580-0859-11ea-9dcb-86152bc33ebf.jpg)

Thank you very much for your great app!

**Comment by mkulesh** [comment]
Hi @Jay000000, thank you for feedback. Could you please install the debug build https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v1.6-debug.apk
and collect the log as follows:
- Open application settings and activate "Developer mode"
- Go to tab MEDIA
- Select NAS
- From the manu bar, select the command "Latest log"
- Select whole text and send it me per email on mikhail.kulesh@gmail.com
This log can help me to solve the problem that you observed.

**Comment by mkulesh** [comment]
Released in v1.6
