### ISSUE TITLE
Seeking track time on NT-503 

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#93]
NT-503 uses time seek format like MM:SS instead of HH:MM:SS.

**Comment by Jay000000** [comment]
CR-N765 likely affected as well. Track position jumps to the first few seconds when seeking.

I'd be happy to provide logs or further information if helpful.

**Comment by mkulesh** [comment]
In which app version do you observe this behavior? If you use version 1.5 or 1.6, could you please install the latest experimental version 2.0 (https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v2.0-release.apk) and check whether this version works better?

**Comment by Jay000000** [comment]
Hi Mikhail, I've observed the bug with version 1.5 (current version from the Play store). 

Similar behaviour with the experimental version 2.0 that you have linked: seeking to around the 50 minutes mark of a one hour file results in a skip to around the 50 seconds mark.

Again many thanks for your swift response, much appreciated!

**Comment by mkulesh** [comment]
Hi @Jay000000, sorry for a late response. On my player, I have never observed such a behavior. Could you please collect the log using the latest nightly build? 

Could you please install the debug build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.6-debug.apk
and collect the log as follows:
- Open application settings and activate "Developer mode"
- Go to tab LISTEN
- Perform time seek that shows the observed behaviour
- From the menu bar, select the command "Latest log"
- Select whole text and send it me per email on mikhail.kulesh@gmail.com

**Comment by mkulesh** [comment]
Released in v1.6
