### ISSUE TITLE
Search function for home media (SMB) playback

### ISSUE THREAD

**Issue by Jay000000** [mkulesh/onpc#97]
The abandoned Onkyo app allows to filter/search the folder list in "home media" by `*pattern*` once fully retrieved.

Would it be possible to implement something similar in the folder view here?

**Comment by mkulesh** [comment]
Hi @Jay000000,
I think it is a good idea. I will try to implement it soon in the version 2.0

**Comment by mkulesh** [comment]
The button "Filter items" is added to MEDIA tab. This button toggles filter edit field:
![media_filter](https://user-images.githubusercontent.com/30557348/79055798-1634ac00-7c50-11ea-839b-7cef149bec0d.png)

**Comment by mkulesh** [comment]
Hi @Jay000000,
I added today the filter field to the MEDIA tab.
Could you please install the latest nightly build and test how does it work for you?
The latest nightly build is here:  https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.12-debug.apk

**Comment by Jay000000** [comment]
Hi @mkulesh,

thank you very much for implementing this feature! From what I've seen testing the current nightly build everything is working as expected.

Again, many thanks!
