### ISSUE TITLE
App Icon - White pixels on border of round icon

### ISSUE THREAD

**Issue by Jay000000** [mkulesh/onpc#98]
Device: OnePlus 5T with OnePlus Launcher (Running Android 9)
Build: 1.6 Debug build retrieved 27.11.2019

![Screenshot (27 11 2019 20_30_32)](https://user-images.githubusercontent.com/57828742/69754090-50942580-1155-11ea-8e07-35827111a41f.jpg)

**Comment by mkulesh** [comment]
Hi @Jay000000, thank you for observation. I will fix it.

**Comment by mkulesh** [comment]
Hi @Jay000000, I now removed any white background from the icon. Could you please install the latest nightly build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.6-debug.apk and test it?

**Comment by Jay000000** [comment]
Hello @mkulesh, instead of the bright pixels there are now black pixels in the right and bottom area with the current debug build. 

Please see this screenshot:
![Screenshot (29 11 2019 16_32_58)](https://user-images.githubusercontent.com/57828742/69878900-65dc9180-12c6-11ea-82bd-4fbe65d45e5b.jpg)

**Comment by mkulesh** [comment]
Hi @Jay000000, thank you, I found a other place where a black color can appear. Hope, now it is fixed. Could you please install the latest nightly build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.6-debug.apk again?

**Comment by mkulesh** [comment]
Released in v1.6

**Comment by Jay000000** [comment]
Using the debug build from today (08.12.2019) the black pixels are still visible on the OnePlus 5T with the stock OnePlus launcher:
![5T](https://user-images.githubusercontent.com/57828742/70391829-8f3da180-19d9-11ea-8382-6c56f283538d.jpg)

On the 7T Pro using Nova Launcher with adaptive Icons everything looks good:
![7T](https://user-images.githubusercontent.com/57828742/70391850-e5124980-19d9-11ea-8825-6f1b70e334fc.jpg)

**Comment by mkulesh** [comment]
Hi @Jay000000,
it seems to be some corner case of the  OnePlus 5T launcher. Currently, I have no ideas more. The app has two icon sets: a round icon for Android 4 and 6 (like https://github.com/mkulesh/onpc/blob/master/app/src/main/res/mipmap-xhdpi/ic_launcher.png) and adaptive icon (https://github.com/mkulesh/onpc/blob/master/app/src/main/res/mipmap-xhdpi/ic_launcher_adapt.png). Both sets have no any black pixels; whole background is transparent. And for me is not clear which icon is used in this launcher... Do you know is it possible to download and install this launcher?

**Comment by Jay000000** [comment]
Hi @mkulesh,

interestingly I have not observed this icon display issues with other apps on the launcher. I would speculate that something goes wrong when resizing and masking the adaptive icon. 

Using Nova Launcher on the 5T the icon looks better, but appears to have some pixels missing in the edge areas:
![Screenshot (12 12 2019 18_49_19)](https://user-images.githubusercontent.com/57828742/70736760-49524780-1d11-11ea-922b-fea24eb4038b.jpg)

For OnePlus devices it is available on the play store: https://play.google.com/store/apps/details?id=net.oneplus.launcher&hl=de

For other makes the APK for Android 9 from XDA should work:
https://www.xda-developers.com/oneplus-launcher-recent-apps-interface-android-pie/

Many thanks for your support! I would not put to much time into this, after all this is very minor.

**Comment by mkulesh** [comment]
Hi @Jay000000,
unfortunately, I have no more ideas how to solve this problem. Sorry, but currently I am not able to fix it.
